"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ITEM_MAP = exports.ITEMS = void 0;
exports.getFlingPower = getFlingPower;
exports.ITEMS = [
    { slug: "", ja: "もちものを選択（なし）", effect: "none" },
    // ── 採用率順（Smogon gen9ubers 2026-02） ──
    { slug: "heavy-duty-boots", ja: "あつぞこブーツ", effect: "none", flingPower: 80 },
    { slug: "leftovers", ja: "たべのこし", effect: "none", flingPower: 10 },
    { slug: "choice-scarf", ja: "こだわりスカーフ", effect: "none", flingPower: 10 },
    { slug: "focus-sash", ja: "きあいのタスキ", effect: "none", flingPower: 10 },
    { slug: "life-orb", ja: "いのちのたま", effect: "life-orb", flingPower: 30 },
    { slug: "loaded-dice", ja: "いかさまダイス", effect: "loaded-dice", flingPower: 30 },
    { slug: "rocky-helmet", ja: "ゴツゴツメット", effect: "rocky-helmet", flingPower: 60 },
    { slug: "choice-specs", ja: "こだわりメガネ", effect: "choice-specs", flingPower: 10 },
    { slug: "choice-band", ja: "こだわりハチマキ", effect: "choice-band", flingPower: 10 },
    { slug: "weakness-policy", ja: "じゃくてんほけん", effect: "none", flingPower: 80 },
    { slug: "assault-vest", ja: "とつげきチョッキ", effect: "assault-vest", flingPower: 80 },
    { slug: "air-balloon", ja: "ふうせん", effect: "none", flingPower: 10 },
    { slug: "booster-energy", ja: "ブーストエナジー", effect: "none", flingPower: 30 },
    { slug: "toxic-orb", ja: "どくどくだま", effect: "none", flingPower: 30 },
    { slug: "lum-berry", ja: "ラムのみ", effect: "none", flingPower: 10 },
    { slug: "sitrus-berry", ja: "オボンのみ", effect: "none", flingPower: 10 },
    { slug: "eviolite", ja: "しんかのきせき", effect: "eviolite", flingPower: 40 },
    { slug: "flame-orb", ja: "かえんだま", effect: "none", flingPower: 30 },
    { slug: "black-sludge", ja: "くろいヘドロ", effect: "none", flingPower: 30 },
    { slug: "expert-belt", ja: "たつじんのおび", effect: "expert-belt", flingPower: 10 },
    { slug: "wide-lens", ja: "ひろいレンズ", effect: "none", flingPower: 10 },
    { slug: "safety-goggles", ja: "ぼうじんゴーグル", effect: "none", flingPower: 80 },
    { slug: "clear-amulet", ja: "クリアチャーム", effect: "none", flingPower: 30 },
    { slug: "mirror-herb", ja: "ミラーハーブ", effect: "none", flingPower: 30 },
    { slug: "covert-cloak", ja: "おんみつマント", effect: "none", flingPower: 30 },
    { slug: "punching-glove", ja: "パンチグローブ", effect: "punching-glove", flingPower: 30 },
    { slug: "iron-ball", ja: "くろいてっきゅう", effect: "none", flingPower: 130 },
    { slug: "scope-lens", ja: "ピントレンズ", effect: "none", flingPower: 30 },
    { slug: "muscle-band", ja: "ちからのハチマキ", effect: "muscle-band", flingPower: 10 },
    { slug: "wise-glasses", ja: "ものしりメガネ", effect: "wise-glasses", flingPower: 10 },
    { slug: "protective-pads", ja: "ぼうごパット", effect: "none", flingPower: 30 },
    { slug: "shed-shell", ja: "きれいなぬけがら", effect: "none", flingPower: 10 },
    { slug: "terrain-extender", ja: "グランドコート", effect: "none", flingPower: 60 },
    // ── タイプ強化アイテム（1.2倍） ──
    { slug: "silk-scarf", ja: "シルクのスカーフ", effect: "type-boost", boostType: "normal", flingPower: 10 },
    { slug: "charcoal", ja: "もくたん", effect: "type-boost", boostType: "fire", flingPower: 30 },
    { slug: "mystic-water", ja: "しんぴのしずく", effect: "type-boost", boostType: "water", flingPower: 30 },
    { slug: "magnet", ja: "じしゃく", effect: "type-boost", boostType: "electric", flingPower: 30 },
    { slug: "miracle-seed", ja: "きせきのタネ", effect: "type-boost", boostType: "grass", flingPower: 30 },
    { slug: "never-melt-ice", ja: "とけないこおり", effect: "type-boost", boostType: "ice", flingPower: 30 },
    { slug: "black-belt", ja: "くろおび", effect: "type-boost", boostType: "fighting", flingPower: 30 },
    { slug: "poison-barb", ja: "どくばり", effect: "type-boost", boostType: "poison", flingPower: 70 },
    { slug: "soft-sand", ja: "やわらかいすな", effect: "type-boost", boostType: "ground", flingPower: 10 },
    { slug: "sharp-beak", ja: "するどいくちばし", effect: "type-boost", boostType: "flying", flingPower: 50 },
    { slug: "twisted-spoon", ja: "まがったスプーン", effect: "type-boost", boostType: "psychic", flingPower: 30 },
    { slug: "silver-powder", ja: "ぎんのこな", effect: "type-boost", boostType: "bug", flingPower: 10 },
    { slug: "hard-stone", ja: "かたいいし", effect: "type-boost", boostType: "rock", flingPower: 100 },
    { slug: "spell-tag", ja: "のろいのおふだ", effect: "type-boost", boostType: "ghost", flingPower: 30 },
    { slug: "dragon-fang", ja: "りゅうのキバ", effect: "type-boost", boostType: "dragon", flingPower: 70 },
    { slug: "black-glasses", ja: "くろいメガネ", effect: "type-boost", boostType: "dark", flingPower: 30 },
    { slug: "metal-coat", ja: "メタルコート", effect: "type-boost", boostType: "steel", flingPower: 30 },
    { slug: "fairy-feather", ja: "ようせいのはね", effect: "type-boost", boostType: "fairy", flingPower: 10 },
    // ── メガストーン ──
    { slug: "charizardite-x", ja: "リザードナイトX", effect: "mega-stone", flingPower: 80 },
    { slug: "charizardite-y", ja: "リザードナイトY", effect: "mega-stone", flingPower: 80 },
    { slug: "kangaskhanite", ja: "ガルーラナイト", effect: "mega-stone", flingPower: 80 },
    { slug: "gengarite", ja: "ゲンガナイト", effect: "mega-stone", flingPower: 80 },
    { slug: "lucarionite", ja: "ルカリオナイト", effect: "mega-stone", flingPower: 80 },
    { slug: "salamencite", ja: "ボーマンダナイト", effect: "mega-stone", flingPower: 80 },
    { slug: "metagrossite", ja: "メタグロスナイト", effect: "mega-stone", flingPower: 80 },
    { slug: "garchompite", ja: "ガブリアスナイト", effect: "mega-stone", flingPower: 80 },
    { slug: "gardevoirite", ja: "サーナイトナイト", effect: "mega-stone", flingPower: 80 },
    { slug: "blazikenite", ja: "バシャーモナイト", effect: "mega-stone", flingPower: 80 },
    { slug: "lopunnite", ja: "ミミロップナイト", effect: "mega-stone", flingPower: 80 },
    { slug: "mawilite", ja: "クチートナイト", effect: "mega-stone", flingPower: 80 },
    { slug: "scizorite", ja: "ハッサムナイト", effect: "mega-stone", flingPower: 80 },
    { slug: "alakazite", ja: "フーディナイト", effect: "mega-stone", flingPower: 80 },
    { slug: "gyaradosite", ja: "ギャラドスナイト", effect: "mega-stone", flingPower: 80 },
    { slug: "venusaurite", ja: "フシギバナナイト", effect: "mega-stone", flingPower: 80 },
    { slug: "blastoisinite", ja: "カメックスナイト", effect: "mega-stone", flingPower: 80 },
    { slug: "beedrillite", ja: "スピアーナイト", effect: "mega-stone", flingPower: 80 },
    { slug: "pidgeotite", ja: "ピジョットナイト", effect: "mega-stone", flingPower: 80 },
    { slug: "slowbronite", ja: "ヤドランナイト", effect: "mega-stone", flingPower: 80 },
    { slug: "aerodactylite", ja: "プテラナイト", effect: "mega-stone", flingPower: 80 },
    { slug: "mewtwonite-x", ja: "ミュウツーナイトX", effect: "mega-stone", flingPower: 80 },
    { slug: "mewtwonite-y", ja: "ミュウツーナイトY", effect: "mega-stone", flingPower: 80 },
    { slug: "ampharosite", ja: "デンリュウナイト", effect: "mega-stone", flingPower: 80 },
    { slug: "steelixite", ja: "ハガネールナイト", effect: "mega-stone", flingPower: 80 },
    { slug: "heracronite", ja: "ヘラクロスナイト", effect: "mega-stone", flingPower: 80 },
    { slug: "houndoominite", ja: "ヘルガナイト", effect: "mega-stone", flingPower: 80 },
    { slug: "tyranitarite", ja: "バンギラスナイト", effect: "mega-stone", flingPower: 80 },
    { slug: "sceptilite", ja: "ジュカインナイト", effect: "mega-stone", flingPower: 80 },
    { slug: "swampertite", ja: "ラグラージナイト", effect: "mega-stone", flingPower: 80 },
    { slug: "sablenite", ja: "ヤミラミナイト", effect: "mega-stone", flingPower: 80 },
    { slug: "aggronite", ja: "ボスゴドラナイト", effect: "mega-stone", flingPower: 80 },
    { slug: "medichamite", ja: "チャーレムナイト", effect: "mega-stone", flingPower: 80 },
    { slug: "manectite", ja: "ライボルトナイト", effect: "mega-stone", flingPower: 80 },
    { slug: "sharpedonite", ja: "サメハダーナイト", effect: "mega-stone", flingPower: 80 },
    { slug: "cameruptite", ja: "バクーダナイト", effect: "mega-stone", flingPower: 80 },
    { slug: "altarianite", ja: "チルタリスナイト", effect: "mega-stone", flingPower: 80 },
    { slug: "banettite", ja: "ジュペッタナイト", effect: "mega-stone", flingPower: 80 },
    { slug: "absolite", ja: "アブソルナイト", effect: "mega-stone", flingPower: 80 },
    { slug: "glalitite", ja: "オニゴーリナイト", effect: "mega-stone", flingPower: 80 },
    { slug: "latiasite", ja: "ラティアスナイト", effect: "mega-stone", flingPower: 80 },
    { slug: "latiosite", ja: "ラティオスナイト", effect: "mega-stone", flingPower: 80 },
    { slug: "abomasite", ja: "ユキノオーナイト", effect: "mega-stone", flingPower: 80 },
    { slug: "galladite", ja: "エルレイドナイト", effect: "mega-stone", flingPower: 80 },
    { slug: "audinite", ja: "タブンネナイト", effect: "mega-stone", flingPower: 80 },
    { slug: "diancite", ja: "ディアンシーナイト", effect: "mega-stone", flingPower: 80 },
    { slug: "pinsirite", ja: "カイロスナイト", effect: "mega-stone", flingPower: 80 },
    // Z-A 新メガストーン
    { slug: "meganiumite", ja: "メガニウムナイト", effect: "mega-stone", flingPower: 80 },
    { slug: "feraligatrite", ja: "オーダイルナイト", effect: "mega-stone", flingPower: 80 },
    { slug: "raichunite-x", ja: "ライチュウナイトX", effect: "mega-stone", flingPower: 80 },
    { slug: "raichunite-y", ja: "ライチュウナイトY", effect: "mega-stone", flingPower: 80 },
    { slug: "clefablite", ja: "ピクシーナイト", effect: "mega-stone", flingPower: 80 },
    { slug: "victreebelite", ja: "ウツボットナイト", effect: "mega-stone", flingPower: 80 },
    { slug: "starmiite", ja: "スターミーナイト", effect: "mega-stone", flingPower: 80 },
    { slug: "dragonitite", ja: "カイリューナイト", effect: "mega-stone", flingPower: 80 },
    { slug: "emboarite", ja: "エンブオーナイト", effect: "mega-stone", flingPower: 80 },
    { slug: "excadrillite", ja: "ドリュウズナイト", effect: "mega-stone", flingPower: 80 },
    { slug: "chandelurite", ja: "シャンデラナイト", effect: "mega-stone", flingPower: 80 },
    { slug: "greninjaite", ja: "ゲッコウガナイト", effect: "mega-stone", flingPower: 80 },
    { slug: "skarmoryite", ja: "エアームドナイト", effect: "mega-stone", flingPower: 80 },
    { slug: "chesnaughtite", ja: "ブリガロンナイト", effect: "mega-stone", flingPower: 80 },
    { slug: "delphoxite", ja: "マフォクシーナイト", effect: "mega-stone", flingPower: 80 },
    { slug: "dragalgite", ja: "ドラミドロナイト", effect: "mega-stone", flingPower: 80 },
    { slug: "malamarite", ja: "カラマネロナイト", effect: "mega-stone", flingPower: 80 },
    { slug: "froslassite", ja: "ユキメノコナイト", effect: "mega-stone", flingPower: 80 },
    { slug: "heatranite", ja: "ヒードランナイト", effect: "mega-stone", flingPower: 80 },
    { slug: "drampite", ja: "ジジーロンナイト", effect: "mega-stone", flingPower: 80 },
    { slug: "darkraite", ja: "ダークライナイト", effect: "mega-stone", flingPower: 80 },
    { slug: "baxcaliburite", ja: "セグレイブナイト", effect: "mega-stone", flingPower: 80 },
    { slug: "floettite", ja: "フラエッテナイト", effect: "mega-stone", flingPower: 80 },
    { slug: "hawluchite", ja: "ルチャブルナイト", effect: "mega-stone", flingPower: 80 },
];
exports.ITEM_MAP = Object.fromEntries(exports.ITEMS.map((i) => [i.slug, i]));
function getFlingPower(itemSlug) {
    if (!itemSlug)
        return null;
    return exports.ITEM_MAP[itemSlug]?.flingPower ?? null;
}
