/**
 * ポケモン別 持ち物採用率ランキング（上位6個、2%以上）
 * Source: Smogon AG+Ubers+OU+UU+RU+NU+PU (2026-02)
 * Auto-generated
 * 登録数: 399体
 */
export const POKEMON_ITEM_USAGE: Record<string, string[]> = {
  "calyrex-shadow": ["focus-sash", "choice-scarf", "life-orb", "heavy-duty-boots"],
  "miraidon": ["heavy-duty-boots", "choice-scarf", "choice-specs", "life-orb", "assault-vest"],
  "koraidon": ["loaded-dice", "choice-scarf", "choice-band"],
  "arceus": ["heavy-duty-boots", "silk-scarf", "leftovers", "life-orb", "lum-berry"],
  "ho-oh": ["heavy-duty-boots", "assault-vest", "leftovers"],
  "kyogre": ["choice-scarf", "choice-specs", "leftovers", "assault-vest"],
  "ting-lu": ["leftovers", "heavy-duty-boots", "assault-vest"],
  "iron-treads": ["booster-energy", "assault-vest", "leftovers", "heavy-duty-boots", "safety-goggles"],
  "alomomola": ["rocky-helmet", "heavy-duty-boots", "leftovers"],
  "calyrex-ice": ["heavy-duty-boots", "choice-band", "leftovers", "focus-sash"],
  "clodsire": ["leftovers", "heavy-duty-boots"],
  "hatterene": ["focus-sash", "leftovers"],
  "kingambit": ["black-glasses", "focus-sash", "leftovers"],
  "skeledirge": ["heavy-duty-boots", "leftovers"],
  "eternatus": ["heavy-duty-boots", "leftovers", "black-sludge", "life-orb"],
  "corviknight": ["leftovers", "rocky-helmet"],
  "necrozma-dusk-mane": ["weakness-policy", "leftovers", "heavy-duty-boots", "lum-berry", "rocky-helmet", "covert-cloak"],
  "flutter-mane": ["booster-energy", "focus-sash"],
  "terapagos": ["heavy-duty-boots", "leftovers"],
  "chien-pao": ["focus-sash", "life-orb", "choice-band"],
  "basculegion": ["focus-sash", "choice-scarf", "life-orb"],
  "blissey": ["heavy-duty-boots", "leftovers"],
  "toxapex": ["leftovers", "rocky-helmet", "black-sludge", "heavy-duty-boots"],
  "dondozo": ["leftovers", "heavy-duty-boots"],
  "urshifu-rapid-strike": ["choice-scarf", "choice-band"],
  "giratina": ["heavy-duty-boots", "leftovers"],
  "deoxys-attack": ["focus-sash", "life-orb"],
  "incineroar": ["leftovers", "heavy-duty-boots"],
  "landorus-therian": ["rocky-helmet", "choice-scarf"],
  "great-tusk": ["booster-energy", "leftovers", "heavy-duty-boots"],
  "mandibuzz": ["heavy-duty-boots", "leftovers"],
  "gholdengo": ["choice-scarf", "air-balloon"],
  "baxcalibur": ["loaded-dice", "leftovers"],
  "ursaluna-bloodmoon": ["life-orb", "assault-vest", "leftovers"],
  "urshifu": ["focus-sash", "choice-band"],
  "pecharunt": ["leftovers", "rocky-helmet", "heavy-duty-boots"],
  "iron-hands": ["life-orb", "assault-vest", "booster-energy"],
  "weezing-galar": ["leftovers", "heavy-duty-boots"],
  "iron-bundle": ["booster-energy", "choice-specs"],
  "chi-yu": ["choice-scarf", "choice-specs"],
  "cyclizar": ["choice-scarf", "heavy-duty-boots"],
  "bellossom": ["leftovers", "focus-sash"],
  "heatran": ["leftovers", "air-balloon"],
  "skarmory": ["rocky-helmet", "leftovers"],
  "vivillon": ["leftovers", "focus-sash"],
  "hoopa-unbound": ["heavy-duty-boots", "life-orb"],
  "houndstone": ["choice-scarf", "focus-sash"],
  "gouging-fire": ["choice-band", "booster-energy"],
  "muk-alola": ["heavy-duty-boots", "leftovers"],
  "scream-tail": ["booster-energy", "leftovers"],
  "brute-bonnet": ["life-orb", "booster-energy"],
  "barraskewda": ["focus-sash", "choice-band"],
  "delibird": ["focus-sash", "choice-band", "choice-scarf"],
  "dachsbun": ["leftovers", "heavy-duty-boots"],
  "ogerpon": ["choice-band", "life-orb"],
  "bisharp": ["eviolite", "expert-belt"],
  "orthworm": ["sitrus-berry", "leftovers"],
  "toedscruel": ["leftovers", "heavy-duty-boots"],
  "pineco": ["heavy-duty-boots", "rocky-helmet"],
  "flamigo": ["focus-sash", "choice-scarf"],
  "qwilfish-hisui": ["life-orb", "eviolite"],
  "lunala": ["heavy-duty-boots", "leftovers"],
  "ribombee": ["focus-sash", "choice-scarf"],
  "deoxys-speed": ["focus-sash", "rocky-helmet"],
  "kyurem-black": ["loaded-dice", "leftovers"],
  "rayquaza": ["focus-sash", "life-orb"],
  "annihilape": ["leftovers", "choice-scarf"],
  "lugia": ["heavy-duty-boots", "leftovers"],
  "mewtwo": ["focus-sash", "choice-specs", "life-orb"],
  "magearna": ["leftovers", "weakness-policy", "air-balloon"],
  "archaludon": ["assault-vest", "heavy-duty-boots", "leftovers"],
  "kyurem-white": ["choice-scarf", "choice-specs", "expert-belt"],
  "walking-wake": ["choice-specs", "choice-scarf"],
  "landorus": ["life-orb", "focus-sash"],
  "zekrom": ["life-orb", "lum-berry", "leftovers"],
  "roaring-moon": ["booster-energy", "choice-band"],
  "dialga": ["leftovers", "life-orb"],
  "palkia": ["focus-sash", "choice-scarf"],
  "spectrier": ["choice-scarf", "focus-sash", "leftovers", "life-orb"],
  "excadrill": ["focus-sash", "air-balloon"],
  "solgaleo": ["leftovers", "weakness-policy"],
  "clefable": ["leftovers", "rocky-helmet"],
  "dugtrio": ["choice-scarf", "leftovers"],
  "gothitelle": ["choice-scarf", "leftovers"],
  "pawmot": ["focus-sash", "choice-scarf"],
  "hippowdon": ["rocky-helmet", "heavy-duty-boots"],
  "volcanion": ["choice-specs", "focus-sash"],
  "meloetta": ["choice-scarf", "heavy-duty-boots"],
  "keldeo": ["choice-specs", "assault-vest"],
  "tentacruel": ["assault-vest", "leftovers"],
  "exeggutor": ["focus-sash", "life-orb"],
  "indeedee-female": ["terrain-extender", "focus-sash"],
  "gothita": ["eviolite", "choice-scarf"],
  "morpeko": ["focus-sash", "heavy-duty-boots"],
  "deoxys": ["focus-sash", "life-orb"],
  "avalugg": ["rocky-helmet", "heavy-duty-boots"],
  "nosepass": ["heavy-duty-boots", "eviolite", "rocky-helmet"],
  "cobalion": ["leftovers", "heavy-duty-boots"],
  "enamorus-therian": ["heavy-duty-boots", "leftovers"],
  "mesprit": ["focus-sash", "leftovers"],
  "iron-valiant": ["booster-energy", "choice-specs"],
  "dragonite": ["heavy-duty-boots", "leftovers", "loaded-dice", "choice-band", "silk-scarf"],
  "dragapult": ["choice-specs", "choice-band", "heavy-duty-boots", "life-orb", "leftovers"],
  "raging-bolt": ["booster-energy", "choice-specs", "leftovers", "assault-vest", "life-orb", "heavy-duty-boots"],
  "slowking-galar": ["heavy-duty-boots", "assault-vest", "leftovers", "black-sludge"],
  "zamazenta": ["leftovers", "heavy-duty-boots", "life-orb", "choice-band"],
  "cinderace": ["heavy-duty-boots", "choice-band"],
  "kyurem": ["choice-specs", "loaded-dice", "leftovers", "assault-vest", "choice-scarf", "heavy-duty-boots"],
  "samurott-hisui": ["assault-vest", "choice-scarf", "focus-sash", "black-glasses", "heavy-duty-boots", "choice-band"],
  "glimmora": ["focus-sash", "choice-scarf"],
  "ceruledge": ["focus-sash", "life-orb", "heavy-duty-boots", "covert-cloak"],
  "rillaboom": ["choice-band", "life-orb", "terrain-extender", "assault-vest", "leftovers"],
  "darkrai": ["heavy-duty-boots", "choice-specs", "choice-scarf", "life-orb", "leftovers", "black-glasses"],
  "zapdos": ["heavy-duty-boots", "choice-specs", "rocky-helmet", "leftovers"],
  "iron-moth": ["booster-energy", "choice-specs"],
  "tyranitar": ["choice-band", "leftovers", "assault-vest", "heavy-duty-boots"],
  "primarina": ["assault-vest", "leftovers", "choice-specs"],
  "tornadus-therian": ["assault-vest", "heavy-duty-boots", "choice-specs", "life-orb"],
  "enamorus": ["choice-scarf", "choice-specs", "leftovers", "life-orb", "heavy-duty-boots"],
  "scizor": ["choice-band", "heavy-duty-boots", "leftovers", "sitrus-berry", "life-orb", "metal-coat"],
  "iron-crown": ["choice-specs", "assault-vest", "booster-energy", "choice-scarf", "weakness-policy"],
  "garchomp": ["rocky-helmet", "loaded-dice", "life-orb"],
  "meowscarada": ["choice-scarf", "choice-band", "heavy-duty-boots", "life-orb", "focus-sash"],
  "hydrapple": ["heavy-duty-boots", "rocky-helmet", "life-orb", "assault-vest", "leftovers", "choice-specs"],
  "ursaluna": ["flame-orb", "leftovers"],
  "tinkaton": ["air-balloon", "leftovers"],
  "araquanid": ["leftovers", "heavy-duty-boots", "focus-sash"],
  "serperior": ["leftovers", "choice-scarf"],
  "weavile": ["heavy-duty-boots", "choice-band", "focus-sash", "life-orb"],
  "lokix": ["choice-band", "heavy-duty-boots", "life-orb", "silver-powder"],
  "sinistcha": ["heavy-duty-boots", "leftovers", "rocky-helmet", "covert-cloak"],
  "hydreigon": ["choice-specs", "leftovers", "choice-scarf", "life-orb"],
  "latios": ["choice-scarf", "choice-specs", "weakness-policy", "covert-cloak"],
  "blaziken": ["life-orb", "focus-sash", "scope-lens", "leftovers", "air-balloon", "heavy-duty-boots"],
  "greninja": ["life-orb", "choice-specs", "loaded-dice"],
  "rotom-wash": ["leftovers", "choice-scarf", "rocky-helmet"],
  "venusaur": ["life-orb", "leftovers"],
  "goodra-hisui": ["assault-vest", "leftovers"],
  "cresselia": ["leftovers", "rocky-helmet", "covert-cloak"],
  "moltres-galar": ["sitrus-berry", "leftovers"],
  "quaquaval": ["assault-vest", "heavy-duty-boots", "leftovers", "choice-band", "life-orb", "focus-sash"],
  "latias": ["weakness-policy", "leftovers", "choice-scarf", "covert-cloak"],
  "slither-wing": ["choice-band", "heavy-duty-boots", "assault-vest", "rocky-helmet", "booster-energy", "life-orb"],
  "arcanine-hisui": ["choice-band", "choice-scarf", "life-orb", "heavy-duty-boots"],
  "thundurus-therian": ["heavy-duty-boots", "choice-specs", "choice-scarf", "leftovers", "life-orb"],
  "zoroark-hisui": ["choice-specs", "focus-sash", "choice-scarf", "heavy-duty-boots", "life-orb", "air-balloon"],
  "manaphy": ["leftovers", "sitrus-berry"],
  "lilligant-hisui": ["life-orb", "loaded-dice", "wide-lens", "focus-sash", "leftovers"],
  "indeedee": ["terrain-extender", "choice-scarf"],
  "iron-boulder": ["booster-energy", "choice-band"],
  "maushold": ["wide-lens", "loaded-dice"],
  "okidogi": ["leftovers", "assault-vest", "choice-scarf", "choice-band"],
  "kingdra": ["choice-specs", "life-orb", "scope-lens"],
  "sandy-shocks": ["booster-energy", "heavy-duty-boots", "choice-scarf", "choice-specs"],
  "iron-jugulis": ["booster-energy", "heavy-duty-boots", "choice-specs"],
  "azumarill": ["sitrus-berry", "assault-vest", "choice-band"],
  "comfey": ["life-orb", "leftovers"],
  "zapdos-galar": ["choice-band", "choice-scarf", "leftovers", "assault-vest"],
  "gengar": ["choice-scarf", "focus-sash", "choice-specs"],
  "chesnaught": ["rocky-helmet", "sitrus-berry", "leftovers", "heavy-duty-boots"],
  "magnezone": ["choice-specs", "assault-vest", "leftovers", "air-balloon", "covert-cloak", "choice-scarf"],
  "metagross": ["choice-band", "assault-vest", "leftovers", "weakness-policy"],
  "empoleon": ["leftovers", "assault-vest", "choice-specs", "life-orb"],
  "mamoswine": ["focus-sash", "choice-band", "loaded-dice", "assault-vest", "life-orb", "leftovers"],
  "armarouge": ["weakness-policy", "focus-sash", "leftovers"],
  "salamence": ["heavy-duty-boots", "life-orb", "leftovers", "choice-specs", "lum-berry"],
  "slowking": ["heavy-duty-boots", "leftovers", "assault-vest", "rocky-helmet"],
  "talonflame": ["heavy-duty-boots", "choice-specs", "choice-band"],
  "gyarados": ["leftovers", "heavy-duty-boots", "lum-berry", "loaded-dice"],
  "kleavor": ["choice-scarf", "focus-sash", "heavy-duty-boots"],
  "toxicroak": ["rocky-helmet", "leftovers", "life-orb"],
  "conkeldurr": ["flame-orb", "assault-vest", "leftovers"],
  "haxorus": ["loaded-dice", "lum-berry", "life-orb", "choice-band"],
  "fezandipiti": ["heavy-duty-boots", "leftovers", "assault-vest"],
  "amoonguss": ["heavy-duty-boots", "rocky-helmet", "black-sludge", "leftovers", "assault-vest"],
  "cloyster": ["focus-sash", "never-melt-ice"],
  "charizard": ["choice-specs", "heavy-duty-boots", "choice-scarf", "sitrus-berry"],
  "gardevoir": ["choice-scarf", "choice-specs", "leftovers", "assault-vest", "focus-sash"],
  "blastoise": ["leftovers", "assault-vest"],
  "crawdaunt": ["choice-band", "life-orb", "focus-sash"],
  "mew": ["weakness-policy", "leftovers", "choice-scarf"],
  "forretress": ["rocky-helmet", "heavy-duty-boots", "leftovers"],
  "porygon-z": ["choice-specs", "choice-scarf", "life-orb"],
  "jolteon": ["heavy-duty-boots", "choice-specs", "flame-orb"],
  "zarude": ["leftovers", "heavy-duty-boots", "life-orb", "choice-scarf", "choice-band"],
  "milotic": ["leftovers", "flame-orb", "rocky-helmet", "assault-vest"],
  "whimsicott": ["life-orb", "leftovers", "focus-sash", "choice-specs"],
  "espeon": ["choice-scarf", "choice-specs", "leftovers", "focus-sash"],
  "jirachi": ["leftovers", "choice-scarf", "weakness-policy", "assault-vest"],
  "frosmoth": ["leftovers", "heavy-duty-boots"],
  "salazzle": ["life-orb", "focus-sash", "leftovers", "heavy-duty-boots"],
  "reuniclus": ["life-orb", "leftovers", "focus-sash", "assault-vest"],
  "gallade": ["choice-scarf", "life-orb", "lum-berry", "assault-vest", "scope-lens", "choice-band"],
  "swampert": ["leftovers", "assault-vest"],
  "regidrago": ["choice-scarf", "choice-specs"],
  "gastrodon": ["leftovers", "heavy-duty-boots"],
  "breloom": ["loaded-dice", "focus-sash", "toxic-orb", "choice-band"],
  "thundurus": ["heavy-duty-boots", "focus-sash", "mirror-herb", "life-orb"],
  "chandelure": ["choice-scarf", "choice-specs"],
  "sylveon": ["leftovers", "choice-specs"],
  "braviary-hisui": ["choice-specs", "life-orb", "weakness-policy", "heavy-duty-boots"],
  "typhlosion-hisui": ["choice-scarf", "choice-specs"],
  "cetitan": ["sitrus-berry", "loaded-dice"],
  "drifblim": ["weakness-policy", "heavy-duty-boots", "sitrus-berry", "choice-scarf", "flame-orb"],
  "klefki": ["leftovers", "rocky-helmet"],
  "lucario": ["life-orb", "focus-sash"],
  "deoxys-defense": ["leftovers", "weakness-policy", "heavy-duty-boots", "rocky-helmet"],
  "azelf": ["focus-sash", "expert-belt", "choice-band", "choice-scarf", "life-orb"],
  "slowbro": ["leftovers", "rocky-helmet", "weakness-policy", "heavy-duty-boots", "assault-vest"],
  "bronzong": ["leftovers", "rocky-helmet"],
  "sableye": ["leftovers", "heavy-duty-boots", "rocky-helmet", "covert-cloak"],
  "snorlax": ["leftovers", "assault-vest"],
  "kilowattrel": ["heavy-duty-boots", "choice-specs", "life-orb"],
  "basculegion-female": ["life-orb", "choice-specs", "choice-scarf"],
  "rotom-heat": ["heavy-duty-boots", "choice-scarf", "leftovers", "choice-specs"],
  "infernape": ["life-orb", "focus-sash", "choice-scarf", "choice-band"],
  "necrozma": ["weakness-policy", "leftovers", "lum-berry"],
  "torterra": ["loaded-dice", "leftovers"],
  "entei": ["choice-band", "mirror-herb", "heavy-duty-boots", "assault-vest"],
  "krookodile": ["choice-scarf", "choice-band", "loaded-dice"],
  "ludicolo": ["life-orb", "leftovers"],
  "diancie": ["leftovers", "weakness-policy"],
  "vileplume": ["rocky-helmet", "leftovers", "life-orb", "black-sludge"],
  "vaporeon": ["leftovers", "heavy-duty-boots"],
  "toxtricity": ["choice-specs", "choice-scarf"],
  "iron-leaves": ["life-orb", "booster-energy", "expert-belt", "choice-band"],
  "donphan": ["heavy-duty-boots", "leftovers", "assault-vest"],
  "glastrier": ["heavy-duty-boots", "assault-vest", "leftovers", "choice-band", "life-orb"],
  "staraptor": ["choice-scarf", "choice-band"],
  "grafaiai": ["heavy-duty-boots", "focus-sash", "leftovers", "choice-scarf"],
  "lycanroc-dusk": ["focus-sash", "life-orb", "choice-band"],
  "leavanny": ["focus-sash", "life-orb", "heavy-duty-boots"],
  "farigiraf": ["leftovers", "focus-sash", "weakness-policy"],
  "ambipom": ["silk-scarf", "life-orb"],
  "quagsire": ["leftovers", "heavy-duty-boots"],
  "yanmega": ["life-orb", "choice-specs", "heavy-duty-boots"],
  "iron-thorns": ["booster-energy", "loaded-dice", "air-balloon"],
  "vikavolt": ["heavy-duty-boots", "choice-specs", "focus-sash", "assault-vest", "rocky-helmet"],
  "beartic": ["loaded-dice", "life-orb", "choice-band"],
  "mienshao": ["choice-scarf", "life-orb", "choice-band"],
  "toucannon": ["assault-vest", "choice-band"],
  "arcanine": ["choice-band", "leftovers", "heavy-duty-boots"],
  "revavroom": ["air-balloon", "life-orb", "leftovers"],
  "cinccino": ["loaded-dice", "heavy-duty-boots"],
  "raikou": ["choice-specs", "leftovers", "air-balloon", "heavy-duty-boots"],
  "brambleghast": ["heavy-duty-boots", "life-orb", "leftovers"],
  "leafeon": ["life-orb", "choice-band", "heavy-duty-boots", "leftovers", "covert-cloak"],
  "bellibolt": ["leftovers", "assault-vest", "rocky-helmet", "heavy-duty-boots"],
  "poliwrath": ["sitrus-berry", "covert-cloak", "leftovers", "life-orb"],
  "noivern": ["heavy-duty-boots", "choice-specs", "choice-scarf"],
  "articuno-galar": ["iron-ball", "weakness-policy", "life-orb", "heavy-duty-boots", "leftovers"],
  "arboliva": ["sitrus-berry", "assault-vest", "leftovers", "choice-specs"],
  "rabsca": ["weakness-policy", "heavy-duty-boots", "focus-sash"],
  "inteleon": ["scope-lens", "choice-specs"],
  "cryogonal": ["heavy-duty-boots", "assault-vest"],
  "tsareena": ["heavy-duty-boots", "assault-vest"],
  "houndoom": ["focus-sash", "choice-scarf", "life-orb"],
  "goodra": ["assault-vest", "leftovers"],
  "dudunsparce": ["leftovers", "silk-scarf"],
  "dragalge": ["choice-specs", "assault-vest", "heavy-duty-boots", "black-sludge", "leftovers"],
  "golduck": ["life-orb", "choice-specs", "leftovers", "assault-vest"],
  "abomasnow": ["heavy-duty-boots", "loaded-dice"],
  "articuno": ["heavy-duty-boots", "choice-specs"],
  "drednaw": ["loaded-dice", "focus-sash"],
  "regice": ["assault-vest", "leftovers"],
  "decidueye-hisui": ["rocky-helmet", "heavy-duty-boots", "choice-band", "choice-scarf", "life-orb"],
  "golem-alola": ["choice-scarf", "choice-band"],
  "heracross": ["flame-orb", "choice-scarf", "loaded-dice"],
  "flygon": ["choice-scarf", "choice-band", "loaded-dice", "leftovers", "life-orb"],
  "electivire": ["life-orb", "leftovers"],
  "scyther": ["eviolite", "heavy-duty-boots", "choice-band"],
  "hitmontop": ["assault-vest", "leftovers"],
  "electrode-hisui": ["choice-specs", "life-orb"],
  "sandslash-alola": ["heavy-duty-boots", "life-orb", "leftovers"],
  "froslass": ["focus-sash", "choice-scarf"],
  "spiritomb": ["leftovers", "choice-scarf", "heavy-duty-boots", "focus-sash"],
  "glaceon": ["choice-specs", "leftovers", "rocky-helmet", "assault-vest"],
  "mudsdale": ["leftovers", "rocky-helmet", "choice-band"],
  "komala": ["assault-vest", "heavy-duty-boots", "leftovers"],
  "malamar": ["leftovers", "assault-vest"],
  "golurk": ["choice-band", "assault-vest", "leftovers"],
  "rhyperior": ["weakness-policy", "assault-vest", "choice-band", "leftovers"],
  "mabosstiff": ["choice-band", "leftovers", "choice-scarf", "assault-vest"],
  "eelektross": ["leftovers", "assault-vest"],
  "lapras": ["leftovers", "covert-cloak", "assault-vest"],
  "veluza": ["sitrus-berry", "choice-scarf"],
  "decidueye": ["leftovers", "heavy-duty-boots", "spell-tag"],
  "zoroark": ["life-orb", "focus-sash"],
  "raichu-alola": ["choice-specs", "life-orb"],
  "palossand": ["leftovers", "heavy-duty-boots", "rocky-helmet"],
  "tornadus": ["heavy-duty-boots", "focus-sash", "life-orb"],
  "florges": ["leftovers", "assault-vest"],
  "munkidori": ["choice-scarf", "assault-vest", "choice-specs"],
  "shiftry": ["focus-sash", "life-orb", "expert-belt"],
  "cramorant": ["heavy-duty-boots", "focus-sash", "rocky-helmet"],
  "masquerain": ["focus-sash", "heavy-duty-boots", "choice-scarf"],
  "honchkrow": ["scope-lens", "life-orb", "focus-sash"],
  "spidops": ["focus-sash", "leftovers", "heavy-duty-boots"],
  "probopass": ["rocky-helmet", "leftovers"],
  "alcremie": ["leftovers", "weakness-policy"],
  "mismagius": ["life-orb", "choice-scarf", "leftovers"],
  "emboar": ["life-orb", "choice-band", "choice-scarf", "assault-vest", "leftovers"],
  "lurantis": ["leftovers", "assault-vest"],
  "delphox": ["air-balloon", "choice-scarf"],
  "rampardos": ["life-orb", "choice-scarf", "choice-band", "focus-sash"],
  "sandaconda": ["leftovers", "rocky-helmet", "focus-sash"],
  "slaking": ["choice-band", "choice-scarf"],
  "lycanroc": ["life-orb", "choice-band", "focus-sash"],
  "avalugg-hisui": ["heavy-duty-boots", "leftovers"],
  "typhlosion": ["choice-scarf", "choice-specs"],
  "altaria": ["heavy-duty-boots", "leftovers"],
  "tauros-paldea-blaze": ["clear-amulet", "leftovers", "choice-band"],
  "medicham": ["focus-sash", "life-orb", "choice-band", "choice-scarf"],
  "hariyama": ["flame-orb", "assault-vest", "sitrus-berry", "leftovers"],
  "magmortar": ["choice-specs", "choice-scarf", "assault-vest"],
  "oricorio-pom-pom": ["heavy-duty-boots", "leftovers", "focus-sash"],
  "carbink": ["black-sludge", "heavy-duty-boots", "leftovers"],
  "rotom": ["choice-scarf", "choice-specs"],
  "sandslash": ["heavy-duty-boots", "choice-band", "life-orb", "rocky-helmet", "leftovers"],
  "cacturne": ["focus-sash", "life-orb", "leftovers"],
  "tatsugiri": ["heavy-duty-boots", "focus-sash", "leftovers", "assault-vest"],
  "terrakion": ["life-orb", "choice-band", "focus-sash", "loaded-dice", "choice-scarf"],
  "tauros-paldea-aqua": ["leftovers", "choice-band", "mystic-water"],
  "coalossal": ["heavy-duty-boots", "rocky-helmet"],
  "hoopa": ["choice-specs", "assault-vest", "choice-scarf", "focus-sash"],
  "eiscue": ["sitrus-berry", "rocky-helmet"],
  "magneton": ["eviolite", "choice-scarf"],
  "ursaring": ["choice-scarf", "eviolite", "flame-orb"],
  "raichu": ["life-orb", "focus-sash"],
  "braviary": ["heavy-duty-boots", "life-orb"],
  "rotom-mow": ["leftovers", "choice-scarf", "rocky-helmet", "choice-specs"],
  "muk": ["heavy-duty-boots", "assault-vest", "black-sludge"],
  "bruxish": ["choice-scarf", "choice-band", "heavy-duty-boots"],
  "tauros": ["life-orb", "assault-vest", "choice-band"],
  "lanturn": ["leftovers", "assault-vest"],
  "clawitzer": ["assault-vest", "choice-specs", "expert-belt"],
  "zangoose": ["toxic-orb", "sitrus-berry", "choice-scarf"],
  "arbok": ["sitrus-berry", "black-sludge"],
  "persian-alola": ["heavy-duty-boots", "rocky-helmet", "choice-band"],
  "wigglytuff": ["leftovers", "assault-vest", "heavy-duty-boots"],
  "oricorio-sensu": ["heavy-duty-boots", "leftovers"],
  "zebstrika": ["life-orb", "mirror-herb", "focus-sash"],
  "magcargo": ["focus-sash", "rocky-helmet", "air-balloon", "heavy-duty-boots"],
  "bastiodon": ["leftovers", "rocky-helmet"],
  "rotom-frost": ["choice-scarf", "heavy-duty-boots", "leftovers"],
  "flapple": ["life-orb", "choice-band", "choice-scarf"],
  "virizion": ["covert-cloak", "leftovers", "heavy-duty-boots", "lum-berry", "assault-vest"],
  "sawsbuck": ["life-orb", "leftovers"],
  "flareon": ["toxic-orb", "flame-orb"],
  "illumise": ["leftovers", "heavy-duty-boots"],
  "hitmonchan": ["punching-glove", "assault-vest"],
  "venomoth": ["heavy-duty-boots", "leftovers", "black-sludge"],
  "weezing": ["black-sludge", "rocky-helmet", "leftovers"],
  "ariados": ["focus-sash", "scope-lens"],
  "appletun": ["leftovers", "heavy-duty-boots"],
  "copperajah": ["choice-band", "leftovers", "life-orb"],
  "dodrio": ["choice-band", "heavy-duty-boots"],
  "shaymin": ["leftovers", "life-orb", "rocky-helmet", "choice-scarf"],
  "haunter": ["focus-sash", "eviolite", "choice-scarf", "choice-specs"],
  "luvdisc": ["focus-sash", "choice-specs", "leftovers"],
  "crabominable": ["choice-band", "assault-vest", "life-orb", "leftovers"],
  "persian": ["silk-scarf", "life-orb"],
  "dipplin": ["eviolite", "sitrus-berry"],
  "dugtrio-alola": ["life-orb", "focus-sash", "choice-band"],
  "lycanroc-midnight": ["life-orb", "choice-band"],
  "oricorio": ["heavy-duty-boots", "leftovers", "focus-sash"],
  "klawf": ["focus-sash", "loaded-dice"],
  "wyrdeer": ["toxic-orb", "assault-vest", "mirror-herb", "leftovers"],
  "psyduck": ["focus-sash", "choice-specs"],
  "sunflora": ["life-orb", "expert-belt", "choice-specs"],
  "cottonee": ["focus-sash", "eviolite"],
  "murkrow": ["eviolite", "focus-sash"],
  "vespiquen": ["heavy-duty-boots", "leftovers"],
  "mightyena": ["life-orb", "black-glasses"],
  "volbeat": ["heavy-duty-boots", "leftovers"],
  "furret": ["life-orb", "heavy-duty-boots"],
  "pyroar": ["choice-specs", "life-orb"],
  "basculin": ["choice-band", "loaded-dice", "choice-scarf", "life-orb"],
  "gumshoos": ["choice-band", "life-orb"],
  "overqwil": ["life-orb", "leftovers"],
  "thwackey": ["terrain-extender", "eviolite"],
  "scovillain": ["choice-specs", "life-orb"],
  "hattrem": ["focus-sash", "eviolite"],
  "lilligant": ["leftovers", "life-orb"],
  "wo-chien": ["leftovers", "heavy-duty-boots"],
  "slowbro-galar": ["heavy-duty-boots", "rocky-helmet"],
  "sneasel": ["focus-sash", "heavy-duty-boots"],
  "qwilfish": ["rocky-helmet", "mystic-water"],
  "grimmsnarl": ["heavy-duty-boots", "choice-band", "leftovers"],
  "bombirdier": ["heavy-duty-boots", "choice-scarf", "lum-berry"],
  "sneasel-hisui": ["leftovers", "eviolite"],
  "skuntank": ["rocky-helmet", "choice-scarf"],
  "rotom-fan": ["choice-specs", "heavy-duty-boots"],
  "falinks": ["punching-glove", "covert-cloak"],
  "glalie": ["sitrus-berry", "assault-vest"],
  "primeape": ["eviolite", "choice-scarf"],
  "trevenant": ["sitrus-berry", "life-orb"],
  "whiscash": ["leftovers", "life-orb"],
  "grookey": ["terrain-extender", "focus-sash", "choice-band"],
};
