import type { PokemonType, BaseStats } from "./types";

export interface MegaForm {
  slug: string;
  baseSlug: string;
  jaName: string;
  types: PokemonType[];
  baseStats: BaseStats;
  ability: string;
  abilityJa: string;
  megaStone: string;
  megaStoneJa: string;
  spriteUrl: string;
}

const S = (id: number) => `https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/${id}.png`;
const ART = (id: number) => `https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/${id}.png`;
const SHOWDOWN = (name: string) => `https://play.pokemonshowdown.com/sprites/gen5/${name}.png`;

export const MEGA_FORMS: MegaForm[] = [
  // --- カントー ---
  { slug: "venusaur-mega", baseSlug: "venusaur", jaName: "メガフシギバナ",
    types: ["grass", "poison"], baseStats: { hp: 80, attack: 100, defense: 123, spAtk: 122, spDef: 120, speed: 80 },
    ability: "thick-fat", abilityJa: "あついしぼう", megaStone: "venusaurite", megaStoneJa: "フシギバナナイト", spriteUrl: S(10033) },
  { slug: "charizard-mega-x", baseSlug: "charizard", jaName: "メガリザードンX",
    types: ["fire", "dragon"], baseStats: { hp: 78, attack: 130, defense: 111, spAtk: 130, spDef: 85, speed: 100 },
    ability: "tough-claws", abilityJa: "かたいツメ", megaStone: "charizardite-x", megaStoneJa: "リザードナイトX", spriteUrl: S(10034) },
  { slug: "charizard-mega-y", baseSlug: "charizard", jaName: "メガリザードンY",
    types: ["fire", "flying"], baseStats: { hp: 78, attack: 104, defense: 78, spAtk: 159, spDef: 115, speed: 100 },
    ability: "drought", abilityJa: "ひでり", megaStone: "charizardite-y", megaStoneJa: "リザードナイトY", spriteUrl: S(10035) },
  { slug: "blastoise-mega", baseSlug: "blastoise", jaName: "メガカメックス",
    types: ["water"], baseStats: { hp: 79, attack: 103, defense: 120, spAtk: 135, spDef: 115, speed: 78 },
    ability: "mega-launcher", abilityJa: "メガランチャー", megaStone: "blastoisinite", megaStoneJa: "カメックスナイト", spriteUrl: S(10036) },
  { slug: "beedrill-mega", baseSlug: "beedrill", jaName: "メガスピアー",
    types: ["bug", "poison"], baseStats: { hp: 65, attack: 150, defense: 40, spAtk: 15, spDef: 80, speed: 145 },
    ability: "adaptability", abilityJa: "てきおうりょく", megaStone: "beedrillite", megaStoneJa: "スピアーナイト", spriteUrl: S(10090) },
  { slug: "pidgeot-mega", baseSlug: "pidgeot", jaName: "メガピジョット",
    types: ["normal", "flying"], baseStats: { hp: 83, attack: 80, defense: 80, spAtk: 135, spDef: 80, speed: 121 },
    ability: "no-guard", abilityJa: "ノーガード", megaStone: "pidgeotite", megaStoneJa: "ピジョットナイト", spriteUrl: S(10073) },
  { slug: "alakazam-mega", baseSlug: "alakazam", jaName: "メガフーディン",
    types: ["psychic"], baseStats: { hp: 55, attack: 50, defense: 65, spAtk: 175, spDef: 105, speed: 150 },
    ability: "trace", abilityJa: "トレース", megaStone: "alakazite", megaStoneJa: "フーディナイト", spriteUrl: S(10037) },
  { slug: "slowbro-mega", baseSlug: "slowbro", jaName: "メガヤドラン",
    types: ["water", "psychic"], baseStats: { hp: 95, attack: 75, defense: 180, spAtk: 130, spDef: 80, speed: 30 },
    ability: "shell-armor", abilityJa: "シェルアーマー", megaStone: "slowbronite", megaStoneJa: "ヤドランナイト", spriteUrl: S(10071) },
  { slug: "gengar-mega", baseSlug: "gengar", jaName: "メガゲンガー",
    types: ["ghost", "poison"], baseStats: { hp: 60, attack: 65, defense: 80, spAtk: 170, spDef: 95, speed: 130 },
    ability: "shadow-tag", abilityJa: "かげふみ", megaStone: "gengarite", megaStoneJa: "ゲンガナイト", spriteUrl: S(10038) },
  { slug: "kangaskhan-mega", baseSlug: "kangaskhan", jaName: "メガガルーラ",
    types: ["normal"], baseStats: { hp: 105, attack: 125, defense: 100, spAtk: 60, spDef: 100, speed: 100 },
    ability: "parental-bond", abilityJa: "おやこあい", megaStone: "kangaskhanite", megaStoneJa: "ガルーラナイト", spriteUrl: S(10039) },
  { slug: "pinsir-mega", baseSlug: "pinsir", jaName: "メガカイロス",
    types: ["bug", "flying"], baseStats: { hp: 65, attack: 155, defense: 120, spAtk: 65, spDef: 90, speed: 105 },
    ability: "aerilate", abilityJa: "スカイスキン", megaStone: "pinsirite", megaStoneJa: "カイロスナイト", spriteUrl: S(10040) },
  { slug: "gyarados-mega", baseSlug: "gyarados", jaName: "メガギャラドス",
    types: ["water", "dark"], baseStats: { hp: 95, attack: 155, defense: 109, spAtk: 70, spDef: 130, speed: 81 },
    ability: "mold-breaker", abilityJa: "かたやぶり", megaStone: "gyaradosite", megaStoneJa: "ギャラドスナイト", spriteUrl: S(10041) },
  { slug: "aerodactyl-mega", baseSlug: "aerodactyl", jaName: "メガプテラ",
    types: ["rock", "flying"], baseStats: { hp: 80, attack: 135, defense: 85, spAtk: 70, spDef: 95, speed: 150 },
    ability: "tough-claws", abilityJa: "かたいツメ", megaStone: "aerodactylite", megaStoneJa: "プテラナイト", spriteUrl: S(10042) },
  { slug: "mewtwo-mega-x", baseSlug: "mewtwo", jaName: "メガミュウツーX",
    types: ["psychic", "fighting"], baseStats: { hp: 106, attack: 190, defense: 100, spAtk: 154, spDef: 100, speed: 130 },
    ability: "steadfast", abilityJa: "ふくつのこころ", megaStone: "mewtwonite-x", megaStoneJa: "ミュウツーナイトX", spriteUrl: S(10043) },
  { slug: "mewtwo-mega-y", baseSlug: "mewtwo", jaName: "メガミュウツーY",
    types: ["psychic"], baseStats: { hp: 106, attack: 150, defense: 70, spAtk: 194, spDef: 120, speed: 140 },
    ability: "insomnia", abilityJa: "ふみん", megaStone: "mewtwonite-y", megaStoneJa: "ミュウツーナイトY", spriteUrl: S(10044) },

  // --- ジョウト ---
  { slug: "ampharos-mega", baseSlug: "ampharos", jaName: "メガデンリュウ",
    types: ["electric", "dragon"], baseStats: { hp: 90, attack: 95, defense: 105, spAtk: 165, spDef: 110, speed: 45 },
    ability: "mold-breaker", abilityJa: "かたやぶり", megaStone: "ampharosite", megaStoneJa: "デンリュウナイト", spriteUrl: S(10045) },
  { slug: "steelix-mega", baseSlug: "steelix", jaName: "メガハガネール",
    types: ["steel", "ground"], baseStats: { hp: 75, attack: 125, defense: 230, spAtk: 55, spDef: 95, speed: 30 },
    ability: "sand-force", abilityJa: "すなのちから", megaStone: "steelixite", megaStoneJa: "ハガネールナイト", spriteUrl: S(10072) },
  { slug: "scizor-mega", baseSlug: "scizor", jaName: "メガハッサム",
    types: ["bug", "steel"], baseStats: { hp: 70, attack: 150, defense: 140, spAtk: 65, spDef: 100, speed: 75 },
    ability: "technician", abilityJa: "テクニシャン", megaStone: "scizorite", megaStoneJa: "ハッサムナイト", spriteUrl: S(10046) },
  { slug: "heracross-mega", baseSlug: "heracross", jaName: "メガヘラクロス",
    types: ["bug", "fighting"], baseStats: { hp: 80, attack: 185, defense: 115, spAtk: 40, spDef: 105, speed: 75 },
    ability: "skill-link", abilityJa: "スキルリンク", megaStone: "heracronite", megaStoneJa: "ヘラクロスナイト", spriteUrl: S(10047) },
  { slug: "houndoom-mega", baseSlug: "houndoom", jaName: "メガヘルガー",
    types: ["dark", "fire"], baseStats: { hp: 75, attack: 90, defense: 90, spAtk: 140, spDef: 90, speed: 115 },
    ability: "solar-power", abilityJa: "サンパワー", megaStone: "houndoominite", megaStoneJa: "ヘルガナイト", spriteUrl: S(10048) },
  { slug: "tyranitar-mega", baseSlug: "tyranitar", jaName: "メガバンギラス",
    types: ["rock", "dark"], baseStats: { hp: 100, attack: 164, defense: 150, spAtk: 95, spDef: 120, speed: 71 },
    ability: "sand-stream", abilityJa: "すなおこし", megaStone: "tyranitarite", megaStoneJa: "バンギラスナイト", spriteUrl: S(10049) },

  // --- ホウエン ---
  { slug: "sceptile-mega", baseSlug: "sceptile", jaName: "メガジュカイン",
    types: ["grass", "dragon"], baseStats: { hp: 70, attack: 110, defense: 75, spAtk: 145, spDef: 85, speed: 145 },
    ability: "lightning-rod", abilityJa: "ひらいしん", megaStone: "sceptilite", megaStoneJa: "ジュカインナイト", spriteUrl: S(10065) },
  { slug: "blaziken-mega", baseSlug: "blaziken", jaName: "メガバシャーモ",
    types: ["fire", "fighting"], baseStats: { hp: 80, attack: 160, defense: 80, spAtk: 130, spDef: 80, speed: 100 },
    ability: "speed-boost", abilityJa: "かそく", megaStone: "blazikenite", megaStoneJa: "バシャーモナイト", spriteUrl: S(10050) },
  { slug: "swampert-mega", baseSlug: "swampert", jaName: "メガラグラージ",
    types: ["water", "ground"], baseStats: { hp: 100, attack: 150, defense: 110, spAtk: 95, spDef: 110, speed: 70 },
    ability: "swift-swim", abilityJa: "すいすい", megaStone: "swampertite", megaStoneJa: "ラグラージナイト", spriteUrl: S(10064) },
  { slug: "gardevoir-mega", baseSlug: "gardevoir", jaName: "メガサーナイト",
    types: ["psychic", "fairy"], baseStats: { hp: 68, attack: 85, defense: 65, spAtk: 165, spDef: 135, speed: 100 },
    ability: "pixilate", abilityJa: "フェアリースキン", megaStone: "gardevoirite", megaStoneJa: "サーナイトナイト", spriteUrl: S(10051) },
  { slug: "sableye-mega", baseSlug: "sableye", jaName: "メガヤミラミ",
    types: ["dark", "ghost"], baseStats: { hp: 50, attack: 85, defense: 125, spAtk: 85, spDef: 115, speed: 20 },
    ability: "magic-bounce", abilityJa: "マジックミラー", megaStone: "sablenite", megaStoneJa: "ヤミラミナイト", spriteUrl: S(10066) },
  { slug: "mawile-mega", baseSlug: "mawile", jaName: "メガクチート",
    types: ["steel", "fairy"], baseStats: { hp: 50, attack: 105, defense: 125, spAtk: 55, spDef: 95, speed: 50 },
    ability: "huge-power", abilityJa: "ちからもち", megaStone: "mawilite", megaStoneJa: "クチートナイト", spriteUrl: S(10052) },
  { slug: "aggron-mega", baseSlug: "aggron", jaName: "メガボスゴドラ",
    types: ["steel"], baseStats: { hp: 70, attack: 140, defense: 230, spAtk: 60, spDef: 80, speed: 50 },
    ability: "filter", abilityJa: "フィルター", megaStone: "aggronite", megaStoneJa: "ボスゴドラナイト", spriteUrl: S(10053) },
  { slug: "medicham-mega", baseSlug: "medicham", jaName: "メガチャーレム",
    types: ["fighting", "psychic"], baseStats: { hp: 60, attack: 100, defense: 85, spAtk: 80, spDef: 85, speed: 100 },
    ability: "pure-power", abilityJa: "ヨガパワー", megaStone: "medichamite", megaStoneJa: "チャーレムナイト", spriteUrl: S(10054) },
  { slug: "manectric-mega", baseSlug: "manectric", jaName: "メガライボルト",
    types: ["electric"], baseStats: { hp: 70, attack: 75, defense: 80, spAtk: 135, spDef: 80, speed: 135 },
    ability: "intimidate", abilityJa: "いかく", megaStone: "manectite", megaStoneJa: "ライボルトナイト", spriteUrl: S(10055) },
  { slug: "sharpedo-mega", baseSlug: "sharpedo", jaName: "メガサメハダー",
    types: ["water", "dark"], baseStats: { hp: 70, attack: 140, defense: 70, spAtk: 110, spDef: 65, speed: 105 },
    ability: "strong-jaw", abilityJa: "がんじょうあご", megaStone: "sharpedonite", megaStoneJa: "サメハダーナイト", spriteUrl: S(10070) },
  { slug: "camerupt-mega", baseSlug: "camerupt", jaName: "メガバクーダ",
    types: ["fire", "ground"], baseStats: { hp: 70, attack: 120, defense: 100, spAtk: 145, spDef: 105, speed: 20 },
    ability: "sheer-force", abilityJa: "ちからずく", megaStone: "cameruptite", megaStoneJa: "バクーダナイト", spriteUrl: S(10087) },
  { slug: "altaria-mega", baseSlug: "altaria", jaName: "メガチルタリス",
    types: ["dragon", "fairy"], baseStats: { hp: 75, attack: 110, defense: 110, spAtk: 110, spDef: 105, speed: 80 },
    ability: "pixilate", abilityJa: "フェアリースキン", megaStone: "altarianite", megaStoneJa: "チルタリスナイト", spriteUrl: S(10067) },
  { slug: "banette-mega", baseSlug: "banette", jaName: "メガジュペッタ",
    types: ["ghost"], baseStats: { hp: 64, attack: 165, defense: 75, spAtk: 93, spDef: 83, speed: 75 },
    ability: "prankster", abilityJa: "いたずらごころ", megaStone: "banettite", megaStoneJa: "ジュペッタナイト", spriteUrl: S(10056) },
  { slug: "absol-mega", baseSlug: "absol", jaName: "メガアブソル",
    types: ["dark"], baseStats: { hp: 65, attack: 150, defense: 60, spAtk: 115, spDef: 60, speed: 115 },
    ability: "magic-bounce", abilityJa: "マジックミラー", megaStone: "absolite", megaStoneJa: "アブソルナイト", spriteUrl: S(10057) },
  { slug: "glalie-mega", baseSlug: "glalie", jaName: "メガオニゴーリ",
    types: ["ice"], baseStats: { hp: 80, attack: 120, defense: 80, spAtk: 120, spDef: 80, speed: 100 },
    ability: "refrigerate", abilityJa: "フリーズスキン", megaStone: "glalitite", megaStoneJa: "オニゴーリナイト", spriteUrl: S(10074) },
  { slug: "salamence-mega", baseSlug: "salamence", jaName: "メガボーマンダ",
    types: ["dragon", "flying"], baseStats: { hp: 95, attack: 145, defense: 130, spAtk: 120, spDef: 90, speed: 120 },
    ability: "aerilate", abilityJa: "スカイスキン", megaStone: "salamencite", megaStoneJa: "ボーマンダナイト", spriteUrl: S(10089) },
  { slug: "metagross-mega", baseSlug: "metagross", jaName: "メガメタグロス",
    types: ["steel", "psychic"], baseStats: { hp: 80, attack: 145, defense: 150, spAtk: 105, spDef: 110, speed: 110 },
    ability: "tough-claws", abilityJa: "かたいツメ", megaStone: "metagrossite", megaStoneJa: "メタグロスナイト", spriteUrl: S(10076) },
  { slug: "latias-mega", baseSlug: "latias", jaName: "メガラティアス",
    types: ["dragon", "psychic"], baseStats: { hp: 80, attack: 100, defense: 120, spAtk: 140, spDef: 150, speed: 110 },
    ability: "levitate", abilityJa: "ふゆう", megaStone: "latiasite", megaStoneJa: "ラティアスナイト", spriteUrl: S(10062) },
  { slug: "latios-mega", baseSlug: "latios", jaName: "メガラティオス",
    types: ["dragon", "psychic"], baseStats: { hp: 80, attack: 130, defense: 100, spAtk: 160, spDef: 120, speed: 110 },
    ability: "levitate", abilityJa: "ふゆう", megaStone: "latiosite", megaStoneJa: "ラティオスナイト", spriteUrl: S(10063) },
  { slug: "rayquaza-mega", baseSlug: "rayquaza", jaName: "メガレックウザ",
    types: ["dragon", "flying"], baseStats: { hp: 105, attack: 180, defense: 100, spAtk: 180, spDef: 100, speed: 115 },
    ability: "delta-stream", abilityJa: "デルタストリーム", megaStone: "none", megaStoneJa: "なし（ガリョウテンセイ）", spriteUrl: S(10079) },

  // --- シンオウ ---
  { slug: "garchomp-mega", baseSlug: "garchomp", jaName: "メガガブリアス",
    types: ["dragon", "ground"], baseStats: { hp: 108, attack: 170, defense: 115, spAtk: 120, spDef: 95, speed: 92 },
    ability: "sand-force", abilityJa: "すなのちから", megaStone: "garchompite", megaStoneJa: "ガブリアスナイト", spriteUrl: S(10058) },
  { slug: "lucario-mega", baseSlug: "lucario", jaName: "メガルカリオ",
    types: ["fighting", "steel"], baseStats: { hp: 70, attack: 145, defense: 88, spAtk: 140, spDef: 70, speed: 112 },
    ability: "adaptability", abilityJa: "てきおうりょく", megaStone: "lucarionite", megaStoneJa: "ルカリオナイト", spriteUrl: S(10059) },
  { slug: "abomasnow-mega", baseSlug: "abomasnow", jaName: "メガユキノオー",
    types: ["grass", "ice"], baseStats: { hp: 90, attack: 132, defense: 105, spAtk: 132, spDef: 105, speed: 30 },
    ability: "snow-warning", abilityJa: "ゆきふらし", megaStone: "abomasite", megaStoneJa: "ユキノオーナイト", spriteUrl: S(10060) },
  { slug: "gallade-mega", baseSlug: "gallade", jaName: "メガエルレイド",
    types: ["psychic", "fighting"], baseStats: { hp: 68, attack: 165, defense: 95, spAtk: 65, spDef: 115, speed: 110 },
    ability: "inner-focus", abilityJa: "せいしんりょく", megaStone: "galladite", megaStoneJa: "エルレイドナイト", spriteUrl: S(10068) },

  // --- イッシュ ---
  { slug: "audino-mega", baseSlug: "audino", jaName: "メガタブンネ",
    types: ["normal", "fairy"], baseStats: { hp: 103, attack: 60, defense: 126, spAtk: 80, spDef: 126, speed: 50 },
    ability: "healer", abilityJa: "いやしのこころ", megaStone: "audinite", megaStoneJa: "タブンネナイト", spriteUrl: S(10069) },

  // --- カロス ---
  { slug: "diancie-mega", baseSlug: "diancie", jaName: "メガディアンシー",
    types: ["rock", "fairy"], baseStats: { hp: 50, attack: 160, defense: 110, spAtk: 160, spDef: 110, speed: 110 },
    ability: "magic-bounce", abilityJa: "マジックミラー", megaStone: "diancite", megaStoneJa: "ディアンシーナイト", spriteUrl: S(10075) },

  // --- ミミロップ ---
  { slug: "lopunny-mega", baseSlug: "lopunny", jaName: "メガミミロップ",
    types: ["normal", "fighting"], baseStats: { hp: 65, attack: 136, defense: 94, spAtk: 54, spDef: 96, speed: 135 },
    ability: "scrappy", abilityJa: "きもったま", megaStone: "lopunnite", megaStoneJa: "ミミロップナイト", spriteUrl: S(10088) },

  // ===========================
  // レジェンズZ-A 新メガシンカ
  // ===========================
  { slug: "meganium-mega", baseSlug: "meganium", jaName: "メガメガニウム",
    types: ["grass", "fairy"], baseStats: { hp: 80, attack: 92, defense: 115, spAtk: 143, spDef: 115, speed: 80 },
    ability: "mega-solar", abilityJa: "メガソーラー", megaStone: "meganiumite", megaStoneJa: "メガニウムナイト", spriteUrl: ART(10282) },
  { slug: "feraligatr-mega", baseSlug: "feraligatr", jaName: "メガオーダイル",
    types: ["water", "dragon"], baseStats: { hp: 85, attack: 160, defense: 125, spAtk: 89, spDef: 93, speed: 78 },
    ability: "dragon-skin", abilityJa: "ドラゴンスキン", megaStone: "feraligatrite", megaStoneJa: "オーダイルナイト", spriteUrl: ART(10283) },
  { slug: "raichu-mega-x", baseSlug: "raichu", jaName: "メガライチュウX",
    types: ["electric"], baseStats: { hp: 60, attack: 135, defense: 95, spAtk: 90, spDef: 95, speed: 110 },
    ability: "surge-surfer", abilityJa: "サーフテール", megaStone: "raichunite-x", megaStoneJa: "ライチュウナイトX", spriteUrl: ART(10304) },
  { slug: "raichu-mega-y", baseSlug: "raichu", jaName: "メガライチュウY",
    types: ["electric"], baseStats: { hp: 60, attack: 100, defense: 55, spAtk: 160, spDef: 80, speed: 130 },
    ability: "surge-surfer", abilityJa: "サーフテール", megaStone: "raichunite-y", megaStoneJa: "ライチュウナイトY", spriteUrl: ART(10305) },
  { slug: "clefable-mega", baseSlug: "clefable", jaName: "メガピクシー",
    types: ["fairy", "flying"], baseStats: { hp: 95, attack: 80, defense: 93, spAtk: 135, spDef: 110, speed: 70 },
    ability: "magic-guard", abilityJa: "マジックガード", megaStone: "clefablite", megaStoneJa: "ピクシーナイト", spriteUrl: ART(10278) },
  { slug: "victreebel-mega", baseSlug: "victreebel", jaName: "メガウツボット",
    types: ["grass", "poison"], baseStats: { hp: 80, attack: 125, defense: 85, spAtk: 135, spDef: 95, speed: 70 },
    ability: "chlorophyll", abilityJa: "ようりょくそ", megaStone: "victreebelite", megaStoneJa: "ウツボットナイト", spriteUrl: ART(10279) },
  { slug: "starmie-mega", baseSlug: "starmie", jaName: "メガスターミー",
    types: ["water", "psychic"], baseStats: { hp: 60, attack: 140, defense: 105, spAtk: 130, spDef: 105, speed: 120 },
    ability: "analytic", abilityJa: "アナライズ", megaStone: "starmiite", megaStoneJa: "スターミーナイト", spriteUrl: ART(10280) },
  { slug: "dragonite-mega", baseSlug: "dragonite", jaName: "メガカイリュー",
    types: ["dragon", "flying"], baseStats: { hp: 91, attack: 124, defense: 115, spAtk: 145, spDef: 125, speed: 100 },
    ability: "multiscale", abilityJa: "マルチスケイル", megaStone: "dragonitite", megaStoneJa: "カイリューナイト", spriteUrl: SHOWDOWN("dragonite-mega") },
  { slug: "emboar-mega", baseSlug: "emboar", jaName: "メガエンブオー",
    types: ["fire", "fighting"], baseStats: { hp: 110, attack: 148, defense: 75, spAtk: 110, spDef: 110, speed: 75 },
    ability: "mold-breaker", abilityJa: "かたやぶり", megaStone: "emboarite", megaStoneJa: "エンブオーナイト", spriteUrl: ART(10286) },
  { slug: "excadrill-mega", baseSlug: "excadrill", jaName: "メガドリュウズ",
    types: ["ground", "steel"], baseStats: { hp: 110, attack: 165, defense: 100, spAtk: 65, spDef: 65, speed: 103 },
    ability: "sand-rush", abilityJa: "すなかき", megaStone: "excadrillite", megaStoneJa: "ドリュウズナイト", spriteUrl: ART(10287) },
  { slug: "chandelure-mega", baseSlug: "chandelure", jaName: "メガシャンデラ",
    types: ["ghost", "fire"], baseStats: { hp: 60, attack: 75, defense: 110, spAtk: 175, spDef: 110, speed: 90 },
    ability: "flash-fire", abilityJa: "もらいび", megaStone: "chandelurite", megaStoneJa: "シャンデラナイト", spriteUrl: ART(10291) },
  { slug: "greninja-mega", baseSlug: "greninja", jaName: "メガゲッコウガ",
    types: ["water", "dark"], baseStats: { hp: 72, attack: 125, defense: 77, spAtk: 133, spDef: 81, speed: 142 },
    ability: "protean", abilityJa: "へんげんじざい", megaStone: "greninjaite", megaStoneJa: "ゲッコウガナイト", spriteUrl: ART(10294) },
  { slug: "skarmory-mega", baseSlug: "skarmory", jaName: "メガエアームド",
    types: ["flying", "steel"], baseStats: { hp: 65, attack: 140, defense: 110, spAtk: 40, spDef: 100, speed: 110 },
    ability: "sturdy", abilityJa: "がんじょう", megaStone: "skarmoryite", megaStoneJa: "エアームドナイト", spriteUrl: ART(10284) },
  { slug: "chesnaught-mega", baseSlug: "chesnaught", jaName: "メガブリガロン",
    types: ["grass", "fighting"], baseStats: { hp: 88, attack: 137, defense: 172, spAtk: 74, spDef: 115, speed: 44 },
    ability: "bulletproof", abilityJa: "ぼうだん", megaStone: "chesnaughtite", megaStoneJa: "ブリガロンナイト", spriteUrl: ART(10292) },
  { slug: "delphox-mega", baseSlug: "delphox", jaName: "メガマフォクシー",
    types: ["fire", "psychic"], baseStats: { hp: 75, attack: 69, defense: 72, spAtk: 159, spDef: 125, speed: 134 },
    ability: "levitate", abilityJa: "ふゆう", megaStone: "delphoxite", megaStoneJa: "マフォクシーナイト", spriteUrl: ART(10293) },
  { slug: "dragalge-mega", baseSlug: "dragalge", jaName: "メガドラミドロ",
    types: ["poison", "dragon"], baseStats: { hp: 65, attack: 85, defense: 105, spAtk: 132, spDef: 163, speed: 44 },
    ability: "adaptability", abilityJa: "てきおうりょく", megaStone: "dragalgite", megaStoneJa: "ドラミドロナイト", spriteUrl: ART(10299) },
  { slug: "malamar-mega", baseSlug: "malamar", jaName: "メガカラマネロ",
    types: ["dark", "psychic"], baseStats: { hp: 86, attack: 102, defense: 88, spAtk: 98, spDef: 120, speed: 88 },
    ability: "contrary", abilityJa: "あまのじゃく", megaStone: "malamarite", megaStoneJa: "カラマネロナイト", spriteUrl: ART(10297) },
  { slug: "floette-mega", baseSlug: "floette", jaName: "メガフラエッテ",
    types: ["fairy"], baseStats: { hp: 74, attack: 85, defense: 87, spAtk: 155, spDef: 148, speed: 102 },
    ability: "flower-veil", abilityJa: "フラワーベール", megaStone: "floettite", megaStoneJa: "フラエッテナイト", spriteUrl: ART(10296) },
  { slug: "hawlucha-mega", baseSlug: "hawlucha", jaName: "メガルチャブル",
    types: ["fighting", "flying"], baseStats: { hp: 78, attack: 137, defense: 100, spAtk: 74, spDef: 93, speed: 118 },
    ability: "mold-breaker", abilityJa: "かたやぶり", megaStone: "hawluchite", megaStoneJa: "ルチャブルナイト", spriteUrl: ART(10300) },
  { slug: "froslass-mega", baseSlug: "froslass", jaName: "メガユキメノコ",
    types: ["ice", "fairy"], baseStats: { hp: 70, attack: 80, defense: 70, spAtk: 140, spDef: 100, speed: 120 },
    ability: "snow-warning", abilityJa: "ゆきふらし", megaStone: "froslassite", megaStoneJa: "ユキメノコナイト", spriteUrl: ART(10285) },
  { slug: "heatran-mega", baseSlug: "heatran", jaName: "メガヒードラン",
    types: ["fire", "steel"], baseStats: { hp: 91, attack: 120, defense: 106, spAtk: 175, spDef: 141, speed: 67 },
    ability: "flash-fire", abilityJa: "もらいび", megaStone: "heatranite", megaStoneJa: "ヒードランナイト", spriteUrl: ART(10311) },
  { slug: "drampa-mega", baseSlug: "drampa", jaName: "メガジジーロン",
    types: ["dragon", "psychic"], baseStats: { hp: 78, attack: 85, defense: 110, spAtk: 160, spDef: 116, speed: 36 },
    ability: "berserk", abilityJa: "ぎゃくじょう", megaStone: "drampite", megaStoneJa: "ジジーロンナイト", spriteUrl: ART(10302) },
  { slug: "darkrai-mega", baseSlug: "darkrai", jaName: "メガダークライ",
    types: ["dark"], baseStats: { hp: 70, attack: 120, defense: 130, spAtk: 165, spDef: 130, speed: 85 },
    ability: "bad-dreams", abilityJa: "ナイトメア", megaStone: "darkraite", megaStoneJa: "ダークライナイト", spriteUrl: ART(10312) },
  { slug: "baxcalibur-mega", baseSlug: "baxcalibur", jaName: "メガセグレイブ",
    types: ["ice", "dragon"], baseStats: { hp: 115, attack: 175, defense: 117, spAtk: 105, spDef: 101, speed: 87 },
    ability: "thermal-exchange", abilityJa: "ねつこうかん", megaStone: "baxcaliburite", megaStoneJa: "セグレイブナイト", spriteUrl: ART(10325) },

  // --- レジェンズZ-A 追加メガシンカ（未登録分） ---
  { slug: "scolipede-mega", baseSlug: "scolipede", jaName: "メガペンドラー",
    types: ["bug", "poison"], baseStats: { hp: 60, attack: 140, defense: 149, spAtk: 75, spDef: 99, speed: 62 },
    ability: "speed-boost", abilityJa: "かそく", megaStone: "scolipedite", megaStoneJa: "ペンドラーナイト", spriteUrl: ART(10288) },
  { slug: "scrafty-mega", baseSlug: "scrafty", jaName: "メガズルズキン",
    types: ["dark", "fighting"], baseStats: { hp: 65, attack: 130, defense: 135, spAtk: 55, spDef: 135, speed: 68 },
    ability: "intimidate", abilityJa: "いかく", megaStone: "scraftite", megaStoneJa: "ズルズキンナイト", spriteUrl: ART(10289) },
  { slug: "eelektross-mega", baseSlug: "eelektross", jaName: "メガシビルドン",
    types: ["electric"], baseStats: { hp: 85, attack: 145, defense: 80, spAtk: 135, spDef: 90, speed: 80 },
    ability: "levitate", abilityJa: "ふゆう", megaStone: "eelektrossite", megaStoneJa: "シビルドンナイト", spriteUrl: ART(10290) },
  { slug: "pyroar-mega", baseSlug: "pyroar", jaName: "メガカエンジシ",
    types: ["fire", "normal"], baseStats: { hp: 86, attack: 88, defense: 92, spAtk: 129, spDef: 86, speed: 126 },
    ability: "rivalry", abilityJa: "とうそうしん", megaStone: "pyroarite", megaStoneJa: "カエンジシナイト", spriteUrl: ART(10295) },
  { slug: "barbaracle-mega", baseSlug: "barbaracle", jaName: "メガガメノデス",
    types: ["rock", "fighting"], baseStats: { hp: 72, attack: 140, defense: 130, spAtk: 64, spDef: 106, speed: 88 },
    ability: "tough-claws", abilityJa: "かたいツメ", megaStone: "barbaraclite", megaStoneJa: "ガメノデスナイト", spriteUrl: ART(10298) },
  { slug: "zygarde-mega", baseSlug: "zygarde", jaName: "メガジガルデ",
    types: ["dragon", "ground"], baseStats: { hp: 216, attack: 70, defense: 91, spAtk: 216, spDef: 85, speed: 100 },
    ability: "aura-break", abilityJa: "オーラブレイク", megaStone: "zygardite", megaStoneJa: "ジガルデナイト", spriteUrl: ART(10301) },
  { slug: "falinks-mega", baseSlug: "falinks", jaName: "メガタイレーツ",
    types: ["fighting"], baseStats: { hp: 65, attack: 135, defense: 135, spAtk: 70, spDef: 65, speed: 100 },
    ability: "battle-armor", abilityJa: "カブトアーマー", megaStone: "falinksite", megaStoneJa: "タイレーツナイト", spriteUrl: ART(10303) },
  { slug: "chimecho-mega", baseSlug: "chimecho", jaName: "メガチリーン",
    types: ["psychic", "steel"], baseStats: { hp: 75, attack: 50, defense: 110, spAtk: 135, spDef: 120, speed: 65 },
    ability: "levitate", abilityJa: "ふゆう", megaStone: "chimechite", megaStoneJa: "チリーンナイト", spriteUrl: ART(10306) },
  { slug: "staraptor-mega", baseSlug: "staraptor", jaName: "メガムクホーク",
    types: ["fighting", "flying"], baseStats: { hp: 85, attack: 140, defense: 100, spAtk: 60, spDef: 90, speed: 110 },
    ability: "intimidate", abilityJa: "いかく", megaStone: "staraptornite", megaStoneJa: "ムクホークナイト", spriteUrl: ART(10308) },
  { slug: "golurk-mega", baseSlug: "golurk", jaName: "メガゴルーグ",
    types: ["ground", "ghost"], baseStats: { hp: 89, attack: 159, defense: 105, spAtk: 70, spDef: 105, speed: 55 },
    ability: "iron-fist", abilityJa: "てつのこぶし", megaStone: "golurkite", megaStoneJa: "ゴルーグナイト", spriteUrl: ART(10313) },
  { slug: "meowstic-mega", baseSlug: "meowstic", jaName: "メガニャオニクス",
    types: ["psychic"], baseStats: { hp: 74, attack: 48, defense: 76, spAtk: 143, spDef: 101, speed: 124 },
    ability: "competitive", abilityJa: "かちき", megaStone: "meowsticite", megaStoneJa: "ニャオニクスナイト", spriteUrl: ART(10314) },
  { slug: "crabominable-mega", baseSlug: "crabominable", jaName: "メガケケンカニ",
    types: ["fighting", "ice"], baseStats: { hp: 97, attack: 157, defense: 122, spAtk: 62, spDef: 107, speed: 33 },
    ability: "iron-fist", abilityJa: "てつのこぶし", megaStone: "crabominite", megaStoneJa: "ケケンカニナイト", spriteUrl: ART(10315) },
  { slug: "golisopod-mega", baseSlug: "golisopod", jaName: "メガグソクムシャ",
    types: ["bug", "steel"], baseStats: { hp: 75, attack: 150, defense: 175, spAtk: 70, spDef: 120, speed: 40 },
    ability: "emergency-exit", abilityJa: "ききかいひ", megaStone: "golisopodite", megaStoneJa: "グソクムシャナイト", spriteUrl: ART(10316) },
  { slug: "magearna-mega", baseSlug: "magearna", jaName: "メガマギアナ",
    types: ["steel", "fairy"], baseStats: { hp: 80, attack: 125, defense: 115, spAtk: 170, spDef: 115, speed: 95 },
    ability: "soul-heart", abilityJa: "ソウルハート", megaStone: "magearnite", megaStoneJa: "マギアナナイト", spriteUrl: ART(10317) },
  { slug: "zeraora-mega", baseSlug: "zeraora", jaName: "メガゼラオラ",
    types: ["electric"], baseStats: { hp: 88, attack: 157, defense: 75, spAtk: 147, spDef: 80, speed: 153 },
    ability: "volt-absorb", abilityJa: "ちくでん", megaStone: "zeraoranite", megaStoneJa: "ゼラオラナイト", spriteUrl: ART(10319) },
  { slug: "scovillain-mega", baseSlug: "scovillain", jaName: "メガスコヴィラン",
    types: ["grass", "fire"], baseStats: { hp: 65, attack: 138, defense: 85, spAtk: 138, spDef: 85, speed: 75 },
    ability: "chlorophyll", abilityJa: "ようりょくそ", megaStone: "scovillainite", megaStoneJa: "スコヴィランナイト", spriteUrl: ART(10320) },
  { slug: "glimmora-mega", baseSlug: "glimmora", jaName: "メガキラフロル",
    types: ["rock", "poison"], baseStats: { hp: 83, attack: 90, defense: 105, spAtk: 150, spDef: 96, speed: 101 },
    ability: "toxic-debris", abilityJa: "どくげしょう", megaStone: "glimmorite", megaStoneJa: "キラフロルナイト", spriteUrl: ART(10321) },
  { slug: "tatsugiri-mega", baseSlug: "tatsugiri", jaName: "メガシャリタツ",
    types: ["dragon", "water"], baseStats: { hp: 68, attack: 65, defense: 90, spAtk: 135, spDef: 125, speed: 92 },
    ability: "commander", abilityJa: "しれいとう", megaStone: "tatsugirite", megaStoneJa: "シャリタツナイト", spriteUrl: ART(10322) },

  // --- Zメガシンカ（DLC メガディメンション） ---
  { slug: "absol-mega-z", baseSlug: "absol", jaName: "メガアブソルZ",
    types: ["dark", "ghost"], baseStats: { hp: 65, attack: 154, defense: 60, spAtk: 75, spDef: 60, speed: 151 },
    ability: "magic-bounce", abilityJa: "マジックミラー", megaStone: "absolite-z", megaStoneJa: "アブソルナイトZ", spriteUrl: ART(10307) },
  { slug: "garchomp-mega-z", baseSlug: "garchomp", jaName: "メガガブリアスZ",
    types: ["dragon"], baseStats: { hp: 108, attack: 130, defense: 85, spAtk: 141, spDef: 85, speed: 151 },
    ability: "sand-force", abilityJa: "すなのちから", megaStone: "garchompite-z", megaStoneJa: "ガブリアスナイトZ", spriteUrl: SHOWDOWN("garchomp-mega") },
  { slug: "lucario-mega-z", baseSlug: "lucario", jaName: "メガルカリオZ",
    types: ["fighting", "steel"], baseStats: { hp: 70, attack: 100, defense: 70, spAtk: 164, spDef: 70, speed: 151 },
    ability: "adaptability", abilityJa: "てきおうりょく", megaStone: "lucarionite-z", megaStoneJa: "ルカリオナイトZ", spriteUrl: ART(10310) },
];

/** ポケモンslugから利用可能なメガシンカフォームを取得 */
export function getMegaForms(baseSlug: string): MegaForm[] {
  return MEGA_FORMS.filter((m) => m.baseSlug === baseSlug);
}

/** メガストーンslugからメガフォームを検索 */
export function getMegaFormByStone(stoneSlug: string): MegaForm | undefined {
  return MEGA_FORMS.find((m) => m.megaStone === stoneSlug);
}
