/**
 * S40（レギュレーションI）上位ポケモンのマスターデータ
 * データソース: sv.pokedb.tokyo/pokemon/list?season=40&rule=0
 * 生成日: 2026-03-27
 */
import type { AbilityEntry } from "./types";

export interface MasterMoveEntry {
  slug: string;
  jaName: string;
}

export interface PokemonMasterEntry {
  slug: string;
  jaName: string;
  rank: number;
  abilities: AbilityEntry[];
  moves: MasterMoveEntry[];
}

/**
 * ポケモンslug → マスターデータ
 * 特性: S40採用率順（最初が最多＝デフォルト選択）
 * 技: S40採用率順
 */
export const POKEMON_MASTER_DATA: Record<string, PokemonMasterEntry> = {
  // 1位: ディンルー
  "ting-lu": {
    slug: "ting-lu",
    jaName: "ディンルー",
    rank: 1,
    abilities: [
      { slug: "vessel-of-ruin", isHidden: false, slot: 1 },
    ],
    moves: [
      { slug: "earthquake", jaName: "じしん" },
      { slug: "ruination", jaName: "カタストロフィ" },
      { slug: "whirlwind", jaName: "ふきとばし" },
      { slug: "stealth-rock", jaName: "ステルスロック" },
      { slug: "payback", jaName: "しっぺがえし" },
      { slug: "spikes", jaName: "まきびし" },
      { slug: "heavy-slam", jaName: "ヘビーボンバー" },
      { slug: "fissure", jaName: "じわれ" },
      { slug: "stone-edge", jaName: "ストーンエッジ" },
      { slug: "rest", jaName: "ねむる" },
    ],
  },
  // 2位: パオジアン
  "chien-pao": {
    slug: "chien-pao",
    jaName: "パオジアン",
    rank: 2,
    abilities: [
      { slug: "sword-of-ruin", isHidden: false, slot: 1 },
    ],
    moves: [
      { slug: "icicle-crash", jaName: "つららおとし" },
      { slug: "sucker-punch", jaName: "ふいうち" },
      { slug: "ice-shard", jaName: "こおりのつぶて" },
      { slug: "swords-dance", jaName: "つるぎのまい" },
      { slug: "crunch", jaName: "かみくだく" },
      { slug: "tera-blast", jaName: "テラバースト" },
      { slug: "sacred-sword", jaName: "せいなるつるぎ" },
      { slug: "sheer-cold", jaName: "ぜったいれいど" },
      { slug: "ice-spinner", jaName: "アイススピナー" },
      { slug: "taunt", jaName: "ちょうはつ" },
    ],
  },
  // 3位: コライドン
  "koraidon": {
    slug: "koraidon",
    jaName: "コライドン",
    rank: 3,
    abilities: [
      { slug: "orichalcum-pulse", isHidden: false, slot: 1 },
    ],
    moves: [
      { slug: "flare-blitz", jaName: "フレアドライブ" },
      { slug: "outrage", jaName: "げきりん" },
      { slug: "scale-shot", jaName: "スケイルショット" },
      { slug: "u-turn", jaName: "とんぼがえり" },
      { slug: "close-combat", jaName: "インファイト" },
      { slug: "flame-charge", jaName: "ニトロチャージ" },
      { slug: "swords-dance", jaName: "つるぎのまい" },
      { slug: "collision-course", jaName: "アクセルブレイク" },
      { slug: "drain-punch", jaName: "ドレインパンチ" },
      { slug: "iron-head", jaName: "アイアンヘッド" },
    ],
  },
  // 4位: バドレックス (黒馬)
  "calyrex-shadow": {
    slug: "calyrex-shadow",
    jaName: "バドレックス (黒馬)",
    rank: 4,
    abilities: [
      { slug: "as-one-spectrier", isHidden: false, slot: 1 },
    ],
    moves: [
      { slug: "astral-barrage", jaName: "アストラルビット" },
      { slug: "grass-knot", jaName: "くさむすび" },
      { slug: "nasty-plot", jaName: "わるだくみ" },
      { slug: "draining-kiss", jaName: "ドレインキッス" },
      { slug: "encore", jaName: "アンコール" },
      { slug: "psychic", jaName: "サイコキネシス" },
      { slug: "trick", jaName: "トリック" },
      { slug: "tera-blast", jaName: "テラバースト" },
      { slug: "psyshock", jaName: "サイコショック" },
      { slug: "substitute", jaName: "みがわり" },
    ],
  },
  // 5位: ミライドン
  "miraidon": {
    slug: "miraidon",
    jaName: "ミライドン",
    rank: 5,
    abilities: [
      { slug: "hadron-engine", isHidden: false, slot: 1 },
    ],
    moves: [
      { slug: "electro-drift", jaName: "イナズマドライブ" },
      { slug: "draco-meteor", jaName: "りゅうせいぐん" },
      { slug: "volt-switch", jaName: "ボルトチェンジ" },
      { slug: "tera-blast", jaName: "テラバースト" },
      { slug: "dazzling-gleam", jaName: "マジカルシャイン" },
      { slug: "parabolic-charge", jaName: "パラボラチャージ" },
      { slug: "agility", jaName: "こうそくいどう" },
      { slug: "u-turn", jaName: "とんぼがえり" },
      { slug: "dragon-pulse", jaName: "りゅうのはどう" },
      { slug: "overheat", jaName: "オーバーヒート" },
    ],
  },
  // 6位: ランドロス (霊獣)
  "landorus-therian": {
    slug: "landorus-therian",
    jaName: "ランドロス (霊獣)",
    rank: 6,
    abilities: [
      { slug: "intimidate", isHidden: false, slot: 1 },
    ],
    moves: [
      { slug: "earthquake", jaName: "じしん" },
      { slug: "u-turn", jaName: "とんぼがえり" },
      { slug: "stealth-rock", jaName: "ステルスロック" },
      { slug: "taunt", jaName: "ちょうはつ" },
      { slug: "rock-tomb", jaName: "がんせきふうじ" },
      { slug: "crunch", jaName: "かみくだく" },
      { slug: "fling", jaName: "なげつける" },
      { slug: "rock-slide", jaName: "いわなだれ" },
      { slug: "tera-blast", jaName: "テラバースト" },
      { slug: "bulldoze", jaName: "じならし" },
    ],
  },
  // 7位: ウーラオス (連撃)
  "urshifu-rapid-strike": {
    slug: "urshifu-rapid-strike",
    jaName: "ウーラオス (連撃)",
    rank: 7,
    abilities: [
      { slug: "unseen-fist", isHidden: false, slot: 1 },
    ],
    moves: [
      { slug: "surging-strikes", jaName: "すいりゅうれんだ" },
      { slug: "aqua-jet", jaName: "アクアジェット" },
      { slug: "close-combat", jaName: "インファイト" },
      { slug: "u-turn", jaName: "とんぼがえり" },
      { slug: "ice-spinner", jaName: "アイススピナー" },
      { slug: "substitute", jaName: "みがわり" },
      { slug: "swords-dance", jaName: "つるぎのまい" },
      { slug: "facade", jaName: "からげんき" },
      { slug: "drain-punch", jaName: "ドレインパンチ" },
      { slug: "low-kick", jaName: "けたぐり" },
    ],
  },
  // 8位: ハバタクカミ
  "flutter-mane": {
    slug: "flutter-mane",
    jaName: "ハバタクカミ",
    rank: 8,
    abilities: [
      { slug: "protosynthesis", isHidden: false, slot: 1 },
    ],
    moves: [
      { slug: "moonblast", jaName: "ムーンフォース" },
      { slug: "shadow-ball", jaName: "シャドーボール" },
      { slug: "thunder-wave", jaName: "でんじは" },
      { slug: "taunt", jaName: "ちょうはつ" },
      { slug: "power-gem", jaName: "パワージェム" },
      { slug: "hex", jaName: "たたりめ" },
      { slug: "pain-split", jaName: "いたみわけ" },
      { slug: "mystical-fire", jaName: "マジカルフレイム" },
      { slug: "charm", jaName: "あまえる" },
      { slug: "calm-mind", jaName: "めいそう" },
    ],
  },
  // 9位: キラフロル
  "glimmora": {
    slug: "glimmora",
    jaName: "キラフロル",
    rank: 9,
    abilities: [
      { slug: "toxic-debris", isHidden: false, slot: 1 },
      { slug: "corrosion", isHidden: true, slot: 3 },
    ],
    moves: [
      { slug: "mortal-spin", jaName: "キラースピン" },
      { slug: "stealth-rock", jaName: "ステルスロック" },
      { slug: "power-gem", jaName: "パワージェム" },
      { slug: "mud-shot", jaName: "マッドショット" },
      { slug: "earth-power", jaName: "だいちのちから" },
      { slug: "endure", jaName: "こらえる" },
      { slug: "toxic-spikes", jaName: "どくびし" },
      { slug: "spiky-shield", jaName: "ニードルガード" },
      { slug: "dazzling-gleam", jaName: "マジカルシャイン" },
      { slug: "spikes", jaName: "まきびし" },
    ],
  },
  // 10位: ホウオウ
  "ho-oh": {
    slug: "ho-oh",
    jaName: "ホウオウ",
    rank: 10,
    abilities: [
      { slug: "regenerator", isHidden: true, slot: 3 },
      { slug: "pressure", isHidden: false, slot: 2 },
    ],
    moves: [
      { slug: "sacred-fire", jaName: "せいなるほのお" },
      { slug: "recover", jaName: "じこさいせい" },
      { slug: "earthquake", jaName: "じしん" },
      { slug: "brave-bird", jaName: "ブレイブバード" },
      { slug: "whirlwind", jaName: "ふきとばし" },
      { slug: "tera-blast", jaName: "テラバースト" },
      { slug: "protect", jaName: "まもる" },
      { slug: "substitute", jaName: "みがわり" },
      { slug: "tailwind", jaName: "おいかぜ" },
      { slug: "giga-drain", jaName: "ギガドレイン" },
    ],
  },
  // 11位: ヘイラッシャ
  "dondozo": {
    slug: "dondozo",
    jaName: "ヘイラッシャ",
    rank: 11,
    abilities: [
      { slug: "unaware", isHidden: false, slot: 1 },
      { slug: "water-veil", isHidden: true, slot: 3 },
      { slug: "oblivious", isHidden: false, slot: 3 },
    ],
    moves: [
      { slug: "rest", jaName: "ねむる" },
      { slug: "protect", jaName: "まもる" },
      { slug: "wave-crash", jaName: "ウェーブタックル" },
      { slug: "fissure", jaName: "じわれ" },
      { slug: "yawn", jaName: "あくび" },
      { slug: "earthquake", jaName: "じしん" },
      { slug: "avalanche", jaName: "ゆきなだれ" },
      { slug: "sleep-talk", jaName: "ねごと" },
      { slug: "liquidation", jaName: "アクアブレイク" },
      { slug: "curse", jaName: "のろい" },
    ],
  },
  // 12位: ザシアン
  "zacian-crowned": {
    slug: "zacian-crowned",
    jaName: "ザシアン",
    rank: 12,
    abilities: [
      { slug: "intrepid-sword", isHidden: false, slot: 1 },
    ],
    moves: [
      { slug: "behemoth-blade", jaName: "きょじゅうざん" },
      { slug: "play-rough", jaName: "じゃれつく" },
      { slug: "trailblaze", jaName: "くさわけ" },
      { slug: "swords-dance", jaName: "つるぎのまい" },
      { slug: "wild-charge", jaName: "ワイルドボルト" },
      { slug: "tera-blast", jaName: "テラバースト" },
      { slug: "close-combat", jaName: "インファイト" },
      { slug: "ice-fang", jaName: "こおりのキバ" },
      { slug: "crunch", jaName: "かみくだく" },
      { slug: "quick-attack", jaName: "でんこうせっか" },
    ],
  },
  // 13位: カイオーガ
  "kyogre": {
    slug: "kyogre",
    jaName: "カイオーガ",
    rank: 13,
    abilities: [
      { slug: "drizzle", isHidden: false, slot: 1 },
    ],
    moves: [
      { slug: "thunder", jaName: "かみなり" },
      { slug: "surf", jaName: "なみのり" },
      { slug: "ice-beam", jaName: "れいとうビーム" },
      { slug: "water-spout", jaName: "しおふき" },
      { slug: "tera-blast", jaName: "テラバースト" },
      { slug: "thunder-wave", jaName: "でんじは" },
      { slug: "origin-pulse", jaName: "こんげんのはどう" },
      { slug: "calm-mind", jaName: "めいそう" },
      { slug: "sheer-cold", jaName: "ぜったいれいど" },
      { slug: "protect", jaName: "まもる" },
    ],
  },
  // 14位: ガチグマ (アカツキ)
  "ursaluna-bloodmoon": {
    slug: "ursaluna-bloodmoon",
    jaName: "ガチグマ (アカツキ)",
    rank: 14,
    abilities: [
      { slug: "minds-eye", isHidden: false, slot: 1 },
    ],
    moves: [
      { slug: "blood-moon", jaName: "ブラッドムーン" },
      { slug: "hyper-voice", jaName: "ハイパーボイス" },
      { slug: "vacuum-wave", jaName: "しんくうは" },
      { slug: "earth-power", jaName: "だいちのちから" },
      { slug: "moonlight", jaName: "つきのひかり" },
      { slug: "calm-mind", jaName: "めいそう" },
      { slug: "moonblast", jaName: "ムーンフォース" },
      { slug: "taunt", jaName: "ちょうはつ" },
      { slug: "yawn", jaName: "あくび" },
      { slug: "protect", jaName: "まもる" },
    ],
  },
  // 15位: カイリュー
  "dragonite": {
    slug: "dragonite",
    jaName: "カイリュー",
    rank: 15,
    abilities: [
      { slug: "multiscale", isHidden: true, slot: 3 },
      { slug: "inner-focus", isHidden: false, slot: 2 },
    ],
    moves: [
      { slug: "extreme-speed", jaName: "しんそく" },
      { slug: "earthquake", jaName: "じしん" },
      { slug: "roost", jaName: "はねやすめ" },
      { slug: "dragon-dance", jaName: "りゅうのまい" },
      { slug: "encore", jaName: "アンコール" },
      { slug: "outrage", jaName: "げきりん" },
      { slug: "scale-shot", jaName: "スケイルショット" },
      { slug: "iron-head", jaName: "アイアンヘッド" },
      { slug: "thunder-wave", jaName: "でんじは" },
      { slug: "fire-spin", jaName: "ほのおのうず" },
    ],
  },
  // 16位: ルナアーラ
  "lunala": {
    slug: "lunala",
    jaName: "ルナアーラ",
    rank: 16,
    abilities: [
      { slug: "shadow-shield", isHidden: false, slot: 1 },
    ],
    moves: [
      { slug: "moongeist-beam", jaName: "シャドーレイ" },
      { slug: "moonblast", jaName: "ムーンフォース" },
      { slug: "moonlight", jaName: "つきのひかり" },
      { slug: "calm-mind", jaName: "めいそう" },
      { slug: "trick-room", jaName: "トリックルーム" },
      { slug: "meteor-beam", jaName: "メテオビーム" },
      { slug: "ice-beam", jaName: "れいとうビーム" },
      { slug: "trick", jaName: "トリック" },
      { slug: "psyshock", jaName: "サイコショック" },
      { slug: "psychic", jaName: "サイコキネシス" },
    ],
  },
  // 17位: グライオン
  "gliscor": {
    slug: "gliscor",
    jaName: "グライオン",
    rank: 17,
    abilities: [
      { slug: "poison-heal", isHidden: true, slot: 3 },
      { slug: "hyper-cutter", isHidden: false, slot: 2 },
      { slug: "sand-veil", isHidden: false, slot: 3 },
    ],
    moves: [
      { slug: "protect", jaName: "まもる" },
      { slug: "substitute", jaName: "みがわり" },
      { slug: "toxic", jaName: "どくどく" },
      { slug: "taunt", jaName: "ちょうはつ" },
      { slug: "earthquake", jaName: "じしん" },
      { slug: "knock-off", jaName: "はたきおとす" },
      { slug: "toxic-spikes", jaName: "どくびし" },
      { slug: "stealth-rock", jaName: "ステルスロック" },
      { slug: "swords-dance", jaName: "つるぎのまい" },
      { slug: "bulldoze", jaName: "じならし" },
    ],
  },
  // 18位: キョジオーン
  "garganacl": {
    slug: "garganacl",
    jaName: "キョジオーン",
    rank: 18,
    abilities: [
      { slug: "purifying-salt", isHidden: false, slot: 1 },
      { slug: "sturdy", isHidden: false, slot: 2 },
      { slug: "clear-body", isHidden: true, slot: 3 },
    ],
    moves: [
      { slug: "salt-cure", jaName: "しおづけ" },
      { slug: "recover", jaName: "じこさいせい" },
      { slug: "protect", jaName: "まもる" },
      { slug: "substitute", jaName: "みがわり" },
      { slug: "stealth-rock", jaName: "ステルスロック" },
      { slug: "fissure", jaName: "じわれ" },
      { slug: "curse", jaName: "のろい" },
      { slug: "explosion", jaName: "だいばくはつ" },
      { slug: "iron-defense", jaName: "てっぺき" },
      { slug: "body-press", jaName: "ボディプレス" },
    ],
  },
  // 19位: ミミッキュ
  "mimikyu": {
    slug: "mimikyu",
    jaName: "ミミッキュ",
    rank: 19,
    abilities: [
      { slug: "disguise", isHidden: false, slot: 1 },
    ],
    moves: [
      { slug: "curse", jaName: "のろい" },
      { slug: "play-rough", jaName: "じゃれつく" },
      { slug: "shadow-sneak", jaName: "かげうち" },
      { slug: "trick-room", jaName: "トリックルーム" },
      { slug: "endure", jaName: "こらえる" },
      { slug: "trick", jaName: "トリック" },
      { slug: "pain-split", jaName: "いたみわけ" },
      { slug: "destiny-bond", jaName: "みちづれ" },
      { slug: "thunder-wave", jaName: "でんじは" },
      { slug: "will-o-wisp", jaName: "おにび" },
    ],
  },
  // 20位: オーロンゲ
  "grimmsnarl": {
    slug: "grimmsnarl",
    jaName: "オーロンゲ",
    rank: 20,
    abilities: [
      { slug: "prankster", isHidden: false, slot: 1 },
      { slug: "frisk", isHidden: false, slot: 2 },
      { slug: "pickpocket", isHidden: true, slot: 3 },
    ],
    moves: [
      { slug: "spirit-break", jaName: "ソウルクラッシュ" },
      { slug: "reflect", jaName: "リフレクター" },
      { slug: "light-screen", jaName: "ひかりのかべ" },
      { slug: "thunder-wave", jaName: "でんじは" },
      { slug: "parting-shot", jaName: "すてゼリフ" },
      { slug: "taunt", jaName: "ちょうはつ" },
      { slug: "sucker-punch", jaName: "ふいうち" },
      { slug: "trick", jaName: "トリック" },
      { slug: "foul-play", jaName: "イカサマ" },
      { slug: "fake-out", jaName: "ねこだまし" },
    ],
  },
  // 21位: ドオー
  "clodsire": {
    slug: "clodsire",
    jaName: "ドオー",
    rank: 21,
    abilities: [
      { slug: "water-absorb", isHidden: false, slot: 1 },
      { slug: "unaware", isHidden: true, slot: 3 },
      { slug: "poison-point", isHidden: false, slot: 3 },
    ],
    moves: [
      { slug: "recover", jaName: "じこさいせい" },
      { slug: "earthquake", jaName: "じしん" },
      { slug: "toxic", jaName: "どくどく" },
      { slug: "toxic-spikes", jaName: "どくびし" },
      { slug: "protect", jaName: "まもる" },
      { slug: "stealth-rock", jaName: "ステルスロック" },
      { slug: "earth-power", jaName: "だいちのちから" },
      { slug: "counter", jaName: "カウンター" },
      { slug: "yawn", jaName: "あくび" },
      { slug: "poison-jab", jaName: "どくづき" },
    ],
  },
  // 22位: バドレックス (白馬)
  "calyrex-ice": {
    slug: "calyrex-ice",
    jaName: "バドレックス (白馬)",
    rank: 22,
    abilities: [
      { slug: "as-one-glastrier", isHidden: false, slot: 1 },
    ],
    moves: [
      { slug: "glacial-lance", jaName: "ブリザードランス" },
      { slug: "trick-room", jaName: "トリックルーム" },
      { slug: "high-horsepower", jaName: "１０まんばりき" },
      { slug: "leech-seed", jaName: "やどりぎのタネ" },
      { slug: "icicle-spear", jaName: "つららばり" },
      { slug: "bullet-seed", jaName: "タネマシンガン" },
      { slug: "protect", jaName: "まもる" },
      { slug: "tera-blast", jaName: "テラバースト" },
      { slug: "substitute", jaName: "みがわり" },
      { slug: "curse", jaName: "のろい" },
    ],
  },
  // 23位: テツノワダチ
  "iron-treads": {
    slug: "iron-treads",
    jaName: "テツノワダチ",
    rank: 23,
    abilities: [
      { slug: "quark-drive", isHidden: false, slot: 1 },
    ],
    moves: [
      { slug: "earthquake", jaName: "じしん" },
      { slug: "knock-off", jaName: "はたきおとす" },
      { slug: "iron-head", jaName: "アイアンヘッド" },
      { slug: "rapid-spin", jaName: "こうそくスピン" },
      { slug: "stealth-rock", jaName: "ステルスロック" },
      { slug: "endeavor", jaName: "がむしゃら" },
      { slug: "ice-spinner", jaName: "アイススピナー" },
      { slug: "bulldoze", jaName: "じならし" },
      { slug: "stone-edge", jaName: "ストーンエッジ" },
      { slug: "supercell-slam", jaName: "サンダーダイブ" },
    ],
  },
  // 24位: ブリジュラス
  "archaludon": {
    slug: "archaludon",
    jaName: "ブリジュラス",
    rank: 24,
    abilities: [
      { slug: "stamina", isHidden: false, slot: 1 },
      { slug: "sturdy", isHidden: false, slot: 2 },
      { slug: "stalwart", isHidden: true, slot: 3 },
    ],
    moves: [
      { slug: "draco-meteor", jaName: "りゅうせいぐん" },
      { slug: "body-press", jaName: "ボディプレス" },
      { slug: "stealth-rock", jaName: "ステルスロック" },
      { slug: "flash-cannon", jaName: "ラスターカノン" },
      { slug: "foul-play", jaName: "イカサマ" },
      { slug: "thunder-wave", jaName: "でんじは" },
      { slug: "electro-shot", jaName: "エレクトロビーム" },
      { slug: "metal-burst", jaName: "メタルバースト" },
      { slug: "steel-beam", jaName: "てっていこうせん" },
      { slug: "mirror-coat", jaName: "ミラーコート" },
    ],
  },
  // 25位: オーガポン
  "ogerpon": {
    slug: "ogerpon",
    jaName: "オーガポン",
    rank: 25,
    abilities: [
      { slug: "mold-breaker", isHidden: false, slot: 1 },
      { slug: "sturdy", isHidden: false, slot: 2 },
      { slug: "water-absorb", isHidden: false, slot: 3 },
      { slug: "defiant", isHidden: false, slot: 4 },
    ],
    moves: [
      { slug: "ivy-cudgel", jaName: "ツタこんぼう" },
      { slug: "horn-leech", jaName: "ウッドホーン" },
      { slug: "knock-off", jaName: "はたきおとす" },
      { slug: "swords-dance", jaName: "つるぎのまい" },
      { slug: "play-rough", jaName: "じゃれつく" },
      { slug: "encore", jaName: "アンコール" },
      { slug: "leech-seed", jaName: "やどりぎのタネ" },
      { slug: "substitute", jaName: "みがわり" },
      { slug: "rock-tomb", jaName: "がんせきふうじ" },
      { slug: "taunt", jaName: "ちょうはつ" },
    ],
  },
  // 26位: イーユイ
  "chi-yu": {
    slug: "chi-yu",
    jaName: "イーユイ",
    rank: 26,
    abilities: [
      { slug: "beads-of-ruin", isHidden: false, slot: 1 },
    ],
    moves: [
      { slug: "dark-pulse", jaName: "あくのはどう" },
      { slug: "flamethrower", jaName: "かえんほうしゃ" },
      { slug: "overheat", jaName: "オーバーヒート" },
      { slug: "psychic", jaName: "サイコキネシス" },
      { slug: "snarl", jaName: "バークアウト" },
      { slug: "tera-blast", jaName: "テラバースト" },
      { slug: "fire-blast", jaName: "だいもんじ" },
      { slug: "lava-plume", jaName: "ふんえん" },
      { slug: "nasty-plot", jaName: "わるだくみ" },
      { slug: "taunt", jaName: "ちょうはつ" },
    ],
  },
  // 27位: ムゲンダイナ
  "eternatus": {
    slug: "eternatus",
    jaName: "ムゲンダイナ",
    rank: 27,
    abilities: [
      { slug: "pressure", isHidden: false, slot: 1 },
    ],
    moves: [
      { slug: "dynamax-cannon", jaName: "ダイマックスほう" },
      { slug: "recover", jaName: "じこさいせい" },
      { slug: "flamethrower", jaName: "かえんほうしゃ" },
      { slug: "sludge-bomb", jaName: "ヘドロばくだん" },
      { slug: "toxic-spikes", jaName: "どくびし" },
      { slug: "protect", jaName: "まもる" },
      { slug: "toxic", jaName: "どくどく" },
      { slug: "cosmic-power", jaName: "コスモパワー" },
      { slug: "substitute", jaName: "みがわり" },
      { slug: "draco-meteor", jaName: "りゅうせいぐん" },
    ],
  },
  // 28位: オオニューラ
  "sneasler": {
    slug: "sneasler",
    jaName: "オオニューラ",
    rank: 28,
    abilities: [
      { slug: "unburden", isHidden: false, slot: 1 },
      { slug: "poison-touch", isHidden: true, slot: 3 },
      { slug: "pressure", isHidden: false, slot: 3 },
    ],
    moves: [
      { slug: "close-combat", jaName: "インファイト" },
      { slug: "dire-claw", jaName: "フェイタルクロー" },
      { slug: "swords-dance", jaName: "つるぎのまい" },
      { slug: "toxic-spikes", jaName: "どくびし" },
      { slug: "acrobatics", jaName: "アクロバット" },
      { slug: "throat-chop", jaName: "じごくづき" },
      { slug: "fake-out", jaName: "ねこだまし" },
      { slug: "taunt", jaName: "ちょうはつ" },
      { slug: "shadow-claw", jaName: "シャドークロー" },
      { slug: "toxic", jaName: "どくどく" },
    ],
  },
  // 29位: ドドゲザン
  "kingambit": {
    slug: "kingambit",
    jaName: "ドドゲザン",
    rank: 29,
    abilities: [
      { slug: "supreme-overlord", isHidden: false, slot: 1 },
      { slug: "defiant", isHidden: false, slot: 2 },
      { slug: "pressure", isHidden: true, slot: 3 },
    ],
    moves: [
      { slug: "sucker-punch", jaName: "ふいうち" },
      { slug: "kowtow-cleave", jaName: "ドゲザン" },
      { slug: "iron-head", jaName: "アイアンヘッド" },
      { slug: "swords-dance", jaName: "つるぎのまい" },
      { slug: "guillotine", jaName: "ハサミギロチン" },
      { slug: "low-kick", jaName: "けたぐり" },
      { slug: "tera-blast", jaName: "テラバースト" },
      { slug: "taunt", jaName: "ちょうはつ" },
      { slug: "brick-break", jaName: "かわらわり" },
      { slug: "metal-burst", jaName: "メタルバースト" },
    ],
  },
  // 30位: ママンボウ
  "alomomola": {
    slug: "alomomola",
    jaName: "ママンボウ",
    rank: 30,
    abilities: [
      { slug: "regenerator", isHidden: true, slot: 3 },
      { slug: "healer", isHidden: false, slot: 2 },
      { slug: "hydration", isHidden: false, slot: 3 },
    ],
    moves: [
      { slug: "flip-turn", jaName: "クイックターン" },
      { slug: "wish", jaName: "ねがいごと" },
      { slug: "protect", jaName: "まもる" },
      { slug: "aqua-jet", jaName: "アクアジェット" },
      { slug: "mirror-coat", jaName: "ミラーコート" },
      { slug: "icy-wind", jaName: "こごえるかぜ" },
      { slug: "healing-wish", jaName: "いやしのねがい" },
      { slug: "scald", jaName: "ねっとう" },
      { slug: "play-rough", jaName: "じゃれつく" },
      { slug: "tickle", jaName: "くすぐる" },
    ],
  },
  // 31位: ガチグマ
  "ursaluna": {
    slug: "ursaluna",
    jaName: "ガチグマ",
    rank: 31,
    abilities: [
      { slug: "guts", isHidden: false, slot: 1 },
      { slug: "bulletproof", isHidden: true, slot: 3 },
      { slug: "unnerve", isHidden: false, slot: 3 },
    ],
    moves: [
      { slug: "facade", jaName: "からげんき" },
      { slug: "earthquake", jaName: "じしん" },
      { slug: "protect", jaName: "まもる" },
      { slug: "crunch", jaName: "かみくだく" },
      { slug: "roar", jaName: "ほえる" },
      { slug: "headlong-rush", jaName: "ぶちかまし" },
      { slug: "drain-punch", jaName: "ドレインパンチ" },
      { slug: "swords-dance", jaName: "つるぎのまい" },
      { slug: "trailblaze", jaName: "くさわけ" },
      { slug: "taunt", jaName: "ちょうはつ" },
    ],
  },
  // 32位: テラパゴス
  "terapagos": {
    slug: "terapagos",
    jaName: "テラパゴス",
    rank: 32,
    abilities: [
      { slug: "tera-shift", isHidden: false, slot: 1 },
    ],
    moves: [
      { slug: "tera-starstorm", jaName: "テラクラスター" },
      { slug: "earth-power", jaName: "だいちのちから" },
      { slug: "calm-mind", jaName: "めいそう" },
      { slug: "rapid-spin", jaName: "こうそくスピン" },
      { slug: "rock-polish", jaName: "ロックカット" },
      { slug: "ice-beam", jaName: "れいとうビーム" },
      { slug: "dark-pulse", jaName: "あくのはどう" },
      { slug: "protect", jaName: "まもる" },
      { slug: "meteor-beam", jaName: "メテオビーム" },
      { slug: "stealth-rock", jaName: "ステルスロック" },
    ],
  },
  // 33位: ハッサム
  "scizor": {
    slug: "scizor",
    jaName: "ハッサム",
    rank: 33,
    abilities: [
      { slug: "technician", isHidden: false, slot: 1 },
      { slug: "swarm", isHidden: false, slot: 2 },
      { slug: "light-metal", isHidden: true, slot: 3 },
    ],
    moves: [
      { slug: "bullet-punch", jaName: "バレットパンチ" },
      { slug: "knock-off", jaName: "はたきおとす" },
      { slug: "u-turn", jaName: "とんぼがえり" },
      { slug: "swords-dance", jaName: "つるぎのまい" },
      { slug: "dual-wingbeat", jaName: "ダブルウイング" },
      { slug: "close-combat", jaName: "インファイト" },
      { slug: "defog", jaName: "きりばらい" },
      { slug: "counter", jaName: "カウンター" },
      { slug: "bug-bite", jaName: "むしくい" },
      { slug: "tera-blast", jaName: "テラバースト" },
    ],
  },
  // 34位: ルギア
  "lugia": {
    slug: "lugia",
    jaName: "ルギア",
    rank: 34,
    abilities: [
      { slug: "multiscale", isHidden: true, slot: 3 },
      { slug: "pressure", isHidden: false, slot: 2 },
    ],
    moves: [
      { slug: "recover", jaName: "じこさいせい" },
      { slug: "psychic-noise", jaName: "サイコノイズ" },
      { slug: "whirlwind", jaName: "ふきとばし" },
      { slug: "calm-mind", jaName: "めいそう" },
      { slug: "aeroblast", jaName: "エアロブラスト" },
      { slug: "substitute", jaName: "みがわり" },
      { slug: "air-slash", jaName: "エアスラッシュ" },
      { slug: "earth-power", jaName: "だいちのちから" },
      { slug: "whirlpool", jaName: "うずしお" },
      { slug: "protect", jaName: "まもる" },
    ],
  },
  // 35位: メタモン
  "ditto": {
    slug: "ditto",
    jaName: "メタモン",
    rank: 35,
    abilities: [
      { slug: "imposter", isHidden: false, slot: 1 },
      { slug: "limber", isHidden: false, slot: 2 },
    ],
    moves: [
      { slug: "transform", jaName: "へんしん" },
    ],
  },
  // 36位: サーフゴー
  "gholdengo": {
    slug: "gholdengo",
    jaName: "サーフゴー",
    rank: 36,
    abilities: [
      { slug: "good-as-gold", isHidden: false, slot: 1 },
    ],
    moves: [
      { slug: "make-it-rain", jaName: "ゴールドラッシュ" },
      { slug: "shadow-ball", jaName: "シャドーボール" },
      { slug: "recover", jaName: "じこさいせい" },
      { slug: "nasty-plot", jaName: "わるだくみ" },
      { slug: "trick", jaName: "トリック" },
      { slug: "reflect", jaName: "リフレクター" },
      { slug: "thunder-wave", jaName: "でんじは" },
      { slug: "psyshock", jaName: "サイコショック" },
      { slug: "thunderbolt", jaName: "１０まんボルト" },
      { slug: "hex", jaName: "たたりめ" },
    ],
  },
  // 37位: ベトベトン (アローラ)
  "muk-alola": {
    slug: "muk-alola",
    jaName: "ベトベトン (アローラ)",
    rank: 37,
    abilities: [
      { slug: "poison-touch", isHidden: false, slot: 1 },
      { slug: "power-of-alchemy", isHidden: false, slot: 2 },
      { slug: "gluttony", isHidden: true, slot: 3 },
    ],
    moves: [
      { slug: "knock-off", jaName: "はたきおとす" },
      { slug: "poison-jab", jaName: "どくづき" },
      { slug: "protect", jaName: "まもる" },
      { slug: "shadow-sneak", jaName: "かげうち" },
      { slug: "poison-fang", jaName: "どくどくのキバ" },
      { slug: "drain-punch", jaName: "ドレインパンチ" },
      { slug: "minimize", jaName: "ちいさくなる" },
      { slug: "clear-smog", jaName: "クリアスモッグ" },
      { slug: "toxic", jaName: "どくどく" },
      { slug: "taunt", jaName: "ちょうはつ" },
    ],
  },
  // 38位: バンギラス
  "tyranitar": {
    slug: "tyranitar",
    jaName: "バンギラス",
    rank: 38,
    abilities: [
      { slug: "sand-stream", isHidden: false, slot: 1 },
      { slug: "unnerve", isHidden: true, slot: 3 },
    ],
    moves: [
      { slug: "knock-off", jaName: "はたきおとす" },
      { slug: "low-kick", jaName: "けたぐり" },
      { slug: "earthquake", jaName: "じしん" },
      { slug: "stealth-rock", jaName: "ステルスロック" },
      { slug: "thunder-wave", jaName: "でんじは" },
      { slug: "stone-edge", jaName: "ストーンエッジ" },
      { slug: "rock-tomb", jaName: "がんせきふうじ" },
      { slug: "iron-head", jaName: "アイアンヘッド" },
      { slug: "rock-blast", jaName: "ロックブラスト" },
      { slug: "rest", jaName: "ねむる" },
    ],
  },
  // 39位: アシレーヌ
  "primarina": {
    slug: "primarina",
    jaName: "アシレーヌ",
    rank: 39,
    abilities: [
      { slug: "torrent", isHidden: false, slot: 1 },
      { slug: "liquid-voice", isHidden: true, slot: 3 },
    ],
    moves: [
      { slug: "moonblast", jaName: "ムーンフォース" },
      { slug: "sparkling-aria", jaName: "うたかたのアリア" },
      { slug: "flip-turn", jaName: "クイックターン" },
      { slug: "aqua-jet", jaName: "アクアジェット" },
      { slug: "encore", jaName: "アンコール" },
      { slug: "shadow-ball", jaName: "シャドーボール" },
      { slug: "psychic-noise", jaName: "サイコノイズ" },
      { slug: "perish-song", jaName: "ほろびのうた" },
      { slug: "calm-mind", jaName: "めいそう" },
      { slug: "draining-kiss", jaName: "ドレインキッス" },
    ],
  },
  // 40位: チオンジェン
  "wo-chien": {
    slug: "wo-chien",
    jaName: "チオンジェン",
    rank: 40,
    abilities: [
      { slug: "tablets-of-ruin", isHidden: false, slot: 1 },
    ],
    moves: [
      { slug: "leech-seed", jaName: "やどりぎのタネ" },
      { slug: "protect", jaName: "まもる" },
      { slug: "substitute", jaName: "みがわり" },
      { slug: "foul-play", jaName: "イカサマ" },
      { slug: "knock-off", jaName: "はたきおとす" },
      { slug: "giga-drain", jaName: "ギガドレイン" },
      { slug: "ruination", jaName: "カタストロフィ" },
      { slug: "snarl", jaName: "バークアウト" },
      { slug: "taunt", jaName: "ちょうはつ" },
      { slug: "ingrain", jaName: "ねをはる" },
    ],
  },
  // 41位: マタドガス (ガラル)
  "weezing-galar": {
    slug: "weezing-galar",
    jaName: "マタドガス (ガラル)",
    rank: 41,
    abilities: [
      { slug: "neutralizing-gas", isHidden: false, slot: 1 },
      { slug: "levitate", isHidden: false, slot: 2 },
      { slug: "misty-surge", isHidden: true, slot: 3 },
    ],
    moves: [
      { slug: "toxic", jaName: "どくどく" },
      { slug: "strange-steam", jaName: "ワンダースチーム" },
      { slug: "toxic-spikes", jaName: "どくびし" },
      { slug: "pain-split", jaName: "いたみわけ" },
      { slug: "protect", jaName: "まもる" },
      { slug: "will-o-wisp", jaName: "おにび" },
      { slug: "taunt", jaName: "ちょうはつ" },
      { slug: "defog", jaName: "きりばらい" },
      { slug: "flamethrower", jaName: "かえんほうしゃ" },
      { slug: "clear-smog", jaName: "クリアスモッグ" },
    ],
  },
  // 42位: ガオガエン
  "incineroar": {
    slug: "incineroar",
    jaName: "ガオガエン",
    rank: 42,
    abilities: [
      { slug: "intimidate", isHidden: true, slot: 3 },
      { slug: "blaze", isHidden: false, slot: 2 },
    ],
    moves: [
      { slug: "knock-off", jaName: "はたきおとす" },
      { slug: "flare-blitz", jaName: "フレアドライブ" },
      { slug: "parting-shot", jaName: "すてゼリフ" },
      { slug: "u-turn", jaName: "とんぼがえり" },
      { slug: "will-o-wisp", jaName: "おにび" },
      { slug: "bulldoze", jaName: "じならし" },
      { slug: "roar", jaName: "ほえる" },
      { slug: "fake-out", jaName: "ねこだまし" },
      { slug: "taunt", jaName: "ちょうはつ" },
      { slug: "darkest-lariat", jaName: "ＤＤラリアット" },
    ],
  },
  // 43位: ネクロズマ (日食)
  "necrozma-dusk-mane": {
    slug: "necrozma-dusk-mane",
    jaName: "ネクロズマ (日食)",
    rank: 43,
    abilities: [
      { slug: "prism-armor", isHidden: false, slot: 1 },
    ],
    moves: [
      { slug: "photon-geyser", jaName: "フォトンゲイザー" },
      { slug: "sunsteel-strike", jaName: "メテオドライブ" },
      { slug: "trick-room", jaName: "トリックルーム" },
      { slug: "dragon-dance", jaName: "りゅうのまい" },
      { slug: "swords-dance", jaName: "つるぎのまい" },
      { slug: "earthquake", jaName: "じしん" },
      { slug: "morning-sun", jaName: "あさのひざし" },
      { slug: "knock-off", jaName: "はたきおとす" },
      { slug: "moonlight", jaName: "つきのひかり" },
      { slug: "substitute", jaName: "みがわり" },
    ],
  },
  // 44位: キノガッサ
  "breloom": {
    slug: "breloom",
    jaName: "キノガッサ",
    rank: 44,
    abilities: [
      { slug: "technician", isHidden: true, slot: 3 },
      { slug: "poison-heal", isHidden: false, slot: 2 },
      { slug: "effect-spore", isHidden: false, slot: 3 },
    ],
    moves: [
      { slug: "spore", jaName: "キノコのほうし" },
      { slug: "bullet-seed", jaName: "タネマシンガン" },
      { slug: "mach-punch", jaName: "マッハパンチ" },
      { slug: "swords-dance", jaName: "つるぎのまい" },
      { slug: "substitute", jaName: "みがわり" },
      { slug: "leech-seed", jaName: "やどりぎのタネ" },
      { slug: "rock-tomb", jaName: "がんせきふうじ" },
      { slug: "bulldoze", jaName: "じならし" },
      { slug: "facade", jaName: "からげんき" },
      { slug: "focus-punch", jaName: "きあいパンチ" },
    ],
  },
  // 45位: レックウザ
  "rayquaza": {
    slug: "rayquaza",
    jaName: "レックウザ",
    rank: 45,
    abilities: [
      { slug: "air-lock", isHidden: false, slot: 1 },
    ],
    moves: [
      { slug: "extreme-speed", jaName: "しんそく" },
      { slug: "dragon-ascent", jaName: "ガリョウテンセイ" },
      { slug: "earthquake", jaName: "じしん" },
      { slug: "swords-dance", jaName: "つるぎのまい" },
      { slug: "draco-meteor", jaName: "りゅうせいぐん" },
      { slug: "u-turn", jaName: "とんぼがえり" },
      { slug: "dragon-dance", jaName: "りゅうのまい" },
      { slug: "overheat", jaName: "オーバーヒート" },
      { slug: "outrage", jaName: "げきりん" },
      { slug: "scale-shot", jaName: "スケイルショット" },
    ],
  },
  // 46位: ラウドボーン
  "skeledirge": {
    slug: "skeledirge",
    jaName: "ラウドボーン",
    rank: 46,
    abilities: [
      { slug: "unaware", isHidden: true, slot: 3 },
      { slug: "blaze", isHidden: false, slot: 2 },
    ],
    moves: [
      { slug: "torch-song", jaName: "フレアソング" },
      { slug: "slack-off", jaName: "なまける" },
      { slug: "will-o-wisp", jaName: "おにび" },
      { slug: "shadow-ball", jaName: "シャドーボール" },
      { slug: "hex", jaName: "たたりめ" },
      { slug: "earth-power", jaName: "だいちのちから" },
      { slug: "yawn", jaName: "あくび" },
      { slug: "encore", jaName: "アンコール" },
      { slug: "alluring-voice", jaName: "みわくのボイス" },
      { slug: "overheat", jaName: "オーバーヒート" },
    ],
  },
  // 47位: ゴリランダー
  "rillaboom": {
    slug: "rillaboom",
    jaName: "ゴリランダー",
    rank: 47,
    abilities: [
      { slug: "grassy-surge", isHidden: true, slot: 3 },
      { slug: "overgrow", isHidden: false, slot: 2 },
    ],
    moves: [
      { slug: "grassy-glide", jaName: "グラススライダー" },
      { slug: "u-turn", jaName: "とんぼがえり" },
      { slug: "knock-off", jaName: "はたきおとす" },
      { slug: "drum-beating", jaName: "ドラムアタック" },
      { slug: "high-horsepower", jaName: "１０まんばりき" },
      { slug: "wood-hammer", jaName: "ウッドハンマー" },
      { slug: "tera-blast", jaName: "テラバースト" },
      { slug: "fake-out", jaName: "ねこだまし" },
      { slug: "swords-dance", jaName: "つるぎのまい" },
      { slug: "endeavor", jaName: "がむしゃら" },
    ],
  },
  // 48位: ドヒドイデ
  "toxapex": {
    slug: "toxapex",
    jaName: "ドヒドイデ",
    rank: 48,
    abilities: [
      { slug: "regenerator", isHidden: true, slot: 3 },
      { slug: "limber", isHidden: false, slot: 2 },
      { slug: "merciless", isHidden: false, slot: 3 },
    ],
    moves: [
      { slug: "recover", jaName: "じこさいせい" },
      { slug: "baneful-bunker", jaName: "トーチカ" },
      { slug: "toxic", jaName: "どくどく" },
      { slug: "toxic-spikes", jaName: "どくびし" },
      { slug: "infestation", jaName: "まとわりつく" },
      { slug: "haze", jaName: "くろいきり" },
      { slug: "chilling-water", jaName: "ひやみず" },
      { slug: "liquidation", jaName: "アクアブレイク" },
      { slug: "poison-jab", jaName: "どくづき" },
      { slug: "acid-spray", jaName: "アシッドボム" },
    ],
  },
  // 49位: エルフーン
  "whimsicott": {
    slug: "whimsicott",
    jaName: "エルフーン",
    rank: 49,
    abilities: [
      { slug: "prankster", isHidden: false, slot: 1 },
      { slug: "chlorophyll", isHidden: true, slot: 3 },
      { slug: "infiltrator", isHidden: false, slot: 3 },
    ],
    moves: [
      { slug: "moonblast", jaName: "ムーンフォース" },
      { slug: "encore", jaName: "アンコール" },
      { slug: "tailwind", jaName: "おいかぜ" },
      { slug: "leech-seed", jaName: "やどりぎのタネ" },
      { slug: "endeavor", jaName: "がむしゃら" },
      { slug: "substitute", jaName: "みがわり" },
      { slug: "memento", jaName: "おきみやげ" },
      { slug: "taunt", jaName: "ちょうはつ" },
      { slug: "protect", jaName: "まもる" },
      { slug: "grass-knot", jaName: "くさむすび" },
    ],
  },
  // 50位: ザマゼンタ
  "zamazenta-crowned": {
    slug: "zamazenta-crowned",
    jaName: "ザマゼンタ",
    rank: 50,
    abilities: [
      { slug: "dauntless-shield", isHidden: false, slot: 1 },
    ],
    moves: [
      { slug: "body-press", jaName: "ボディプレス" },
      { slug: "iron-defense", jaName: "てっぺき" },
      { slug: "behemoth-bash", jaName: "きょじゅうだん" },
      { slug: "heavy-slam", jaName: "ヘビーボンバー" },
      { slug: "agility", jaName: "こうそくいどう" },
      { slug: "crunch", jaName: "かみくだく" },
      { slug: "substitute", jaName: "みがわり" },
      { slug: "trailblaze", jaName: "くさわけ" },
      { slug: "light-screen", jaName: "ひかりのかべ" },
      { slug: "reflect", jaName: "リフレクター" },
    ],
  },
  // 51位: ウーラオス (一撃)
  "urshifu-single-strike": {
    slug: "urshifu-single-strike",
    jaName: "ウーラオス (一撃)",
    rank: 51,
    abilities: [
      { slug: "unseen-fist", isHidden: false, slot: 1 },
    ],
    moves: [
      { slug: "wicked-blow", jaName: "あんこくきょうだ" },
      { slug: "sucker-punch", jaName: "ふいうち" },
      { slug: "close-combat", jaName: "インファイト" },
      { slug: "swords-dance", jaName: "つるぎのまい" },
      { slug: "drain-punch", jaName: "ドレインパンチ" },
      { slug: "u-turn", jaName: "とんぼがえり" },
      { slug: "iron-head", jaName: "アイアンヘッド" },
      { slug: "taunt", jaName: "ちょうはつ" },
      { slug: "counter", jaName: "カウンター" },
      { slug: "poison-jab", jaName: "どくづき" },
    ],
  },
  // 52位: テツノツツミ
  "iron-bundle": {
    slug: "iron-bundle",
    jaName: "テツノツツミ",
    rank: 52,
    abilities: [
      { slug: "quark-drive", isHidden: false, slot: 1 },
    ],
    moves: [
      { slug: "freeze-dry", jaName: "フリーズドライ" },
      { slug: "hydro-pump", jaName: "ハイドロポンプ" },
      { slug: "encore", jaName: "アンコール" },
      { slug: "substitute", jaName: "みがわり" },
      { slug: "ice-beam", jaName: "れいとうビーム" },
      { slug: "flip-turn", jaName: "クイックターン" },
      { slug: "tera-blast", jaName: "テラバースト" },
      { slug: "taunt", jaName: "ちょうはつ" },
      { slug: "blizzard", jaName: "ふぶき" },
      { slug: "protect", jaName: "まもる" },
    ],
  },
  // 53位: テツノブジン
  "iron-valiant": {
    slug: "iron-valiant",
    jaName: "テツノブジン",
    rank: 53,
    abilities: [
      { slug: "quark-drive", isHidden: false, slot: 1 },
    ],
    moves: [
      { slug: "destiny-bond", jaName: "みちづれ" },
      { slug: "close-combat", jaName: "インファイト" },
      { slug: "moonblast", jaName: "ムーンフォース" },
      { slug: "spirit-break", jaName: "ソウルクラッシュ" },
      { slug: "encore", jaName: "アンコール" },
      { slug: "knock-off", jaName: "はたきおとす" },
      { slug: "shadow-sneak", jaName: "かげうち" },
      { slug: "thunder-wave", jaName: "でんじは" },
      { slug: "taunt", jaName: "ちょうはつ" },
      { slug: "vacuum-wave", jaName: "しんくうは" },
    ],
  },
  // 54位: ラッキー
  "chansey": {
    slug: "chansey",
    jaName: "ラッキー",
    rank: 54,
    abilities: [
      { slug: "natural-cure", isHidden: false, slot: 1 },
      { slug: "serene-grace", isHidden: false, slot: 2 },
      { slug: "healer", isHidden: true, slot: 3 },
    ],
    moves: [
      { slug: "soft-boiled", jaName: "タマゴうみ" },
      { slug: "seismic-toss", jaName: "ちきゅうなげ" },
      { slug: "shadow-ball", jaName: "シャドーボール" },
      { slug: "thunder-wave", jaName: "でんじは" },
      { slug: "stealth-rock", jaName: "ステルスロック" },
      { slug: "calm-mind", jaName: "めいそう" },
      { slug: "charm", jaName: "あまえる" },
      { slug: "icy-wind", jaName: "こごえるかぜ" },
      { slug: "sing", jaName: "うたう" },
      { slug: "light-screen", jaName: "ひかりのかべ" },
    ],
  },
  // 55位: マスカーニャ
  "meowscarada": {
    slug: "meowscarada",
    jaName: "マスカーニャ",
    rank: 55,
    abilities: [
      { slug: "protean", isHidden: true, slot: 3 },
      { slug: "overgrow", isHidden: false, slot: 2 },
    ],
    moves: [
      { slug: "flower-trick", jaName: "トリックフラワー" },
      { slug: "knock-off", jaName: "はたきおとす" },
      { slug: "sucker-punch", jaName: "ふいうち" },
      { slug: "toxic-spikes", jaName: "どくびし" },
      { slug: "triple-axel", jaName: "トリプルアクセル" },
      { slug: "u-turn", jaName: "とんぼがえり" },
      { slug: "trick", jaName: "トリック" },
      { slug: "play-rough", jaName: "じゃれつく" },
      { slug: "taunt", jaName: "ちょうはつ" },
      { slug: "tera-blast", jaName: "テラバースト" },
    ],
  },
  // 56位: ドーブル
  "smeargle": {
    slug: "smeargle",
    jaName: "ドーブル",
    rank: 56,
    abilities: [
      { slug: "moody", isHidden: true, slot: 3 },
      { slug: "own-tempo", isHidden: false, slot: 2 },
      { slug: "technician", isHidden: false, slot: 3 },
    ],
    moves: [
      { slug: "baton-pass", jaName: "バトンタッチ" },
      { slug: "spore", jaName: "キノコのほうし" },
      { slug: "minimize", jaName: "ちいさくなる" },
      { slug: "taunt", jaName: "ちょうはつ" },
      { slug: "sticky-web", jaName: "ねばねばネット" },
      { slug: "nuzzle", jaName: "ほっぺすりすり" },
      { slug: "ingrain", jaName: "ねをはる" },
      { slug: "substitute", jaName: "みがわり" },
      { slug: "endeavor", jaName: "がむしゃら" },
      { slug: "shell-smash", jaName: "からをやぶる" },
    ],
  },
  // 57位: ヒードラン
  "heatran": {
    slug: "heatran",
    jaName: "ヒードラン",
    rank: 57,
    abilities: [
      { slug: "flash-fire", isHidden: false, slot: 1 },
      { slug: "flame-body", isHidden: true, slot: 3 },
    ],
    moves: [
      { slug: "magma-storm", jaName: "マグマストーム" },
      { slug: "earth-power", jaName: "だいちのちから" },
      { slug: "taunt", jaName: "ちょうはつ" },
      { slug: "protect", jaName: "まもる" },
      { slug: "flash-cannon", jaName: "ラスターカノン" },
      { slug: "power-gem", jaName: "パワージェム" },
      { slug: "tera-blast", jaName: "テラバースト" },
      { slug: "lava-plume", jaName: "ふんえん" },
      { slug: "stealth-rock", jaName: "ステルスロック" },
      { slug: "overheat", jaName: "オーバーヒート" },
    ],
  },
  // 58位: グラードン
  "groudon": {
    slug: "groudon",
    jaName: "グラードン",
    rank: 58,
    abilities: [
      { slug: "drought", isHidden: false, slot: 1 },
    ],
    moves: [
      { slug: "earthquake", jaName: "じしん" },
      { slug: "heat-crash", jaName: "ヒートスタンプ" },
      { slug: "stealth-rock", jaName: "ステルスロック" },
      { slug: "will-o-wisp", jaName: "おにび" },
      { slug: "precipice-blades", jaName: "だんがいのつるぎ" },
      { slug: "stone-edge", jaName: "ストーンエッジ" },
      { slug: "rock-tomb", jaName: "がんせきふうじ" },
      { slug: "fissure", jaName: "じわれ" },
      { slug: "crunch", jaName: "かみくだく" },
      { slug: "rock-slide", jaName: "いわなだれ" },
    ],
  },
  // 59位: マリルリ
  "azumarill": {
    slug: "azumarill",
    jaName: "マリルリ",
    rank: 59,
    abilities: [
      { slug: "huge-power", isHidden: false, slot: 1 },
      { slug: "thick-fat", isHidden: false, slot: 2 },
      { slug: "sap-sipper", isHidden: true, slot: 3 },
    ],
    moves: [
      { slug: "aqua-jet", jaName: "アクアジェット" },
      { slug: "play-rough", jaName: "じゃれつく" },
      { slug: "liquidation", jaName: "アクアブレイク" },
      { slug: "whirlpool", jaName: "うずしお" },
      { slug: "perish-song", jaName: "ほろびのうた" },
      { slug: "protect", jaName: "まもる" },
      { slug: "knock-off", jaName: "はたきおとす" },
      { slug: "encore", jaName: "アンコール" },
      { slug: "belly-drum", jaName: "はらだいこ" },
      { slug: "tera-blast", jaName: "テラバースト" },
    ],
  },
  // 60位: ブラックキュレム
  "kyurem-black": {
    slug: "kyurem-black",
    jaName: "ブラックキュレム",
    rank: 60,
    abilities: [
      { slug: "teravolt", isHidden: false, slot: 1 },
    ],
    moves: [
      { slug: "icicle-spear", jaName: "つららばり" },
      { slug: "dragon-dance", jaName: "りゅうのまい" },
      { slug: "fusion-bolt", jaName: "クロスサンダー" },
      { slug: "scale-shot", jaName: "スケイルショット" },
      { slug: "substitute", jaName: "みがわり" },
      { slug: "tera-blast", jaName: "テラバースト" },
      { slug: "outrage", jaName: "げきりん" },
      { slug: "reflect", jaName: "リフレクター" },
      { slug: "freeze-shock", jaName: "フリーズボルト" },
      { slug: "shadow-claw", jaName: "シャドークロー" },
    ],
  },
  // 61位: ガブリアス
  "garchomp": {
    slug: "garchomp",
    jaName: "ガブリアス",
    rank: 61,
    abilities: [
      { slug: "rough-skin", isHidden: true, slot: 3 },
      { slug: "sand-veil", isHidden: false, slot: 2 },
    ],
    moves: [
      { slug: "earthquake", jaName: "じしん" },
      { slug: "stealth-rock", jaName: "ステルスロック" },
      { slug: "spikes", jaName: "まきびし" },
      { slug: "bulldoze", jaName: "じならし" },
      { slug: "swords-dance", jaName: "つるぎのまい" },
      { slug: "scale-shot", jaName: "スケイルショット" },
      { slug: "iron-head", jaName: "アイアンヘッド" },
      { slug: "outrage", jaName: "げきりん" },
      { slug: "breaking-swipe", jaName: "ワイドブレイカー" },
      { slug: "dragon-tail", jaName: "ドラゴンテール" },
    ],
  },
  // 62位: ウネルミナモ
  "walking-wake": {
    slug: "walking-wake",
    jaName: "ウネルミナモ",
    rank: 62,
    abilities: [
      { slug: "protosynthesis", isHidden: false, slot: 1 },
    ],
    moves: [
      { slug: "hydro-steam", jaName: "ハイドロスチーム" },
      { slug: "flamethrower", jaName: "かえんほうしゃ" },
      { slug: "draco-meteor", jaName: "りゅうせいぐん" },
      { slug: "flip-turn", jaName: "クイックターン" },
      { slug: "aqua-jet", jaName: "アクアジェット" },
      { slug: "dragon-pulse", jaName: "りゅうのはどう" },
      { slug: "tera-blast", jaName: "テラバースト" },
      { slug: "snarl", jaName: "バークアウト" },
      { slug: "substitute", jaName: "みがわり" },
      { slug: "knock-off", jaName: "はたきおとす" },
    ],
  },
  // 63位: カバルドン
  "hippowdon": {
    slug: "hippowdon",
    jaName: "カバルドン",
    rank: 63,
    abilities: [
      { slug: "sand-stream", isHidden: false, slot: 1 },
      { slug: "sand-force", isHidden: true, slot: 3 },
    ],
    moves: [
      { slug: "earthquake", jaName: "じしん" },
      { slug: "yawn", jaName: "あくび" },
      { slug: "stealth-rock", jaName: "ステルスロック" },
      { slug: "slack-off", jaName: "なまける" },
      { slug: "roar", jaName: "ほえる" },
      { slug: "whirlwind", jaName: "ふきとばし" },
      { slug: "crunch", jaName: "かみくだく" },
      { slug: "ice-fang", jaName: "こおりのキバ" },
      { slug: "body-press", jaName: "ボディプレス" },
      { slug: "tera-blast", jaName: "テラバースト" },
    ],
  },
  // 64位: ポリゴン２
  "porygon2": {
    slug: "porygon2",
    jaName: "ポリゴン２",
    rank: 64,
    abilities: [
      { slug: "trace", isHidden: false, slot: 1 },
      { slug: "download", isHidden: false, slot: 2 },
      { slug: "analytic", isHidden: true, slot: 3 },
    ],
    moves: [
      { slug: "recover", jaName: "じこさいせい" },
      { slug: "foul-play", jaName: "イカサマ" },
      { slug: "ice-beam", jaName: "れいとうビーム" },
      { slug: "tri-attack", jaName: "トライアタック" },
      { slug: "thunder-wave", jaName: "でんじは" },
      { slug: "trick-room", jaName: "トリックルーム" },
      { slug: "tera-blast", jaName: "テラバースト" },
      { slug: "shadow-ball", jaName: "シャドーボール" },
      { slug: "discharge", jaName: "ほうでん" },
      { slug: "eerie-impulse", jaName: "かいでんぱ" },
    ],
  },
  // 65位: ソウブレイズ
  "ceruledge": {
    slug: "ceruledge",
    jaName: "ソウブレイズ",
    rank: 65,
    abilities: [
      { slug: "flash-fire", isHidden: false, slot: 1 },
      { slug: "weak-armor", isHidden: true, slot: 3 },
    ],
    moves: [
      { slug: "bitter-blade", jaName: "むねんのつるぎ" },
      { slug: "shadow-sneak", jaName: "かげうち" },
      { slug: "bulk-up", jaName: "ビルドアップ" },
      { slug: "swords-dance", jaName: "つるぎのまい" },
      { slug: "taunt", jaName: "ちょうはつ" },
      { slug: "poltergeist", jaName: "ポルターガイスト" },
      { slug: "tera-blast", jaName: "テラバースト" },
      { slug: "substitute", jaName: "みがわり" },
      { slug: "close-combat", jaName: "インファイト" },
      { slug: "destiny-bond", jaName: "みちづれ" },
    ],
  },
  // 66位: アラブルタケ
  "brute-bonnet": {
    slug: "brute-bonnet",
    jaName: "アラブルタケ",
    rank: 66,
    abilities: [
      { slug: "protosynthesis", isHidden: false, slot: 1 },
    ],
    moves: [
      { slug: "spore", jaName: "キノコのほうし" },
      { slug: "synthesis", jaName: "こうごうせい" },
      { slug: "sucker-punch", jaName: "ふいうち" },
      { slug: "crunch", jaName: "かみくだく" },
      { slug: "bullet-seed", jaName: "タネマシンガン" },
      { slug: "clear-smog", jaName: "クリアスモッグ" },
      { slug: "seed-bomb", jaName: "タネばくだん" },
      { slug: "payback", jaName: "しっぺがえし" },
      { slug: "tera-blast", jaName: "テラバースト" },
      { slug: "substitute", jaName: "みがわり" },
    ],
  },
  // 67位: ウルガモス
  "volcarona": {
    slug: "volcarona",
    jaName: "ウルガモス",
    rank: 67,
    abilities: [
      { slug: "flame-body", isHidden: false, slot: 1 },
      { slug: "swarm", isHidden: true, slot: 3 },
    ],
    moves: [
      { slug: "quiver-dance", jaName: "ちょうのまい" },
      { slug: "fiery-dance", jaName: "ほのおのまい" },
      { slug: "morning-sun", jaName: "あさのひざし" },
      { slug: "bug-buzz", jaName: "むしのさざめき" },
      { slug: "giga-drain", jaName: "ギガドレイン" },
      { slug: "tera-blast", jaName: "テラバースト" },
      { slug: "will-o-wisp", jaName: "おにび" },
      { slug: "flamethrower", jaName: "かえんほうしゃ" },
      { slug: "substitute", jaName: "みがわり" },
      { slug: "whirlwind", jaName: "ふきとばし" },
    ],
  },
  // 68位: ドラパルト
  "dragapult": {
    slug: "dragapult",
    jaName: "ドラパルト",
    rank: 68,
    abilities: [
      { slug: "infiltrator", isHidden: false, slot: 1 },
      { slug: "cursed-body", isHidden: true, slot: 3 },
      { slug: "clear-body", isHidden: false, slot: 3 },
    ],
    moves: [
      { slug: "dragon-darts", jaName: "ドラゴンアロー" },
      { slug: "sucker-punch", jaName: "ふいうち" },
      { slug: "will-o-wisp", jaName: "おにび" },
      { slug: "u-turn", jaName: "とんぼがえり" },
      { slug: "thunder-wave", jaName: "でんじは" },
      { slug: "curse", jaName: "のろい" },
      { slug: "hex", jaName: "たたりめ" },
      { slug: "tera-blast", jaName: "テラバースト" },
      { slug: "light-screen", jaName: "ひかりのかべ" },
      { slug: "phantom-force", jaName: "ゴーストダイブ" },
    ],
  },
  // 69位: バシャーモ
  "blaziken": {
    slug: "blaziken",
    jaName: "バシャーモ",
    rank: 69,
    abilities: [
      { slug: "speed-boost", isHidden: true, slot: 3 },
      { slug: "blaze", isHidden: false, slot: 2 },
    ],
    moves: [
      { slug: "knock-off", jaName: "はたきおとす" },
      { slug: "close-combat", jaName: "インファイト" },
      { slug: "reversal", jaName: "きしかいせい" },
      { slug: "baton-pass", jaName: "バトンタッチ" },
      { slug: "swords-dance", jaName: "つるぎのまい" },
      { slug: "detect", jaName: "みきり" },
      { slug: "protect", jaName: "まもる" },
      { slug: "endure", jaName: "こらえる" },
      { slug: "bulk-up", jaName: "ビルドアップ" },
      { slug: "flare-blitz", jaName: "フレアドライブ" },
    ],
  },
  // 70位: ゴチルゼル
  "gothitelle": {
    slug: "gothitelle",
    jaName: "ゴチルゼル",
    rank: 70,
    abilities: [
      { slug: "shadow-tag", isHidden: true, slot: 3 },
      { slug: "frisk", isHidden: false, slot: 2 },
      { slug: "competitive", isHidden: false, slot: 3 },
    ],
    moves: [
      { slug: "rest", jaName: "ねむる" },
      { slug: "calm-mind", jaName: "めいそう" },
      { slug: "charm", jaName: "あまえる" },
      { slug: "taunt", jaName: "ちょうはつ" },
      { slug: "tera-blast", jaName: "テラバースト" },
      { slug: "stored-power", jaName: "アシストパワー" },
      { slug: "psychic-noise", jaName: "サイコノイズ" },
      { slug: "trick", jaName: "トリック" },
      { slug: "substitute", jaName: "みがわり" },
      { slug: "imprison", jaName: "ふういん" },
    ],
  },
  // 71位: アーマーガア
  "corviknight": {
    slug: "corviknight",
    jaName: "アーマーガア",
    rank: 71,
    abilities: [
      { slug: "pressure", isHidden: false, slot: 1 },
      { slug: "mirror-armor", isHidden: true, slot: 3 },
      { slug: "unnerve", isHidden: false, slot: 3 },
    ],
    moves: [
      { slug: "roost", jaName: "はねやすめ" },
      { slug: "body-press", jaName: "ボディプレス" },
      { slug: "taunt", jaName: "ちょうはつ" },
      { slug: "iron-defense", jaName: "てっぺき" },
      { slug: "u-turn", jaName: "とんぼがえり" },
      { slug: "iron-head", jaName: "アイアンヘッド" },
      { slug: "defog", jaName: "きりばらい" },
      { slug: "protect", jaName: "まもる" },
      { slug: "light-screen", jaName: "ひかりのかべ" },
      { slug: "brave-bird", jaName: "ブレイブバード" },
    ],
  },
  // 72位: オリーヴァ
  "arboliva": {
    slug: "arboliva",
    jaName: "オリーヴァ",
    rank: 72,
    abilities: [
      { slug: "seed-sower", isHidden: false, slot: 1 },
      { slug: "harvest", isHidden: true, slot: 3 },
    ],
    moves: [
      { slug: "giga-drain", jaName: "ギガドレイン" },
      { slug: "earth-power", jaName: "だいちのちから" },
      { slug: "mirror-coat", jaName: "ミラーコート" },
      { slug: "alluring-voice", jaName: "みわくのボイス" },
      { slug: "leech-seed", jaName: "やどりぎのタネ" },
      { slug: "tera-blast", jaName: "テラバースト" },
      { slug: "strength-sap", jaName: "ちからをすいとる" },
      { slug: "protect", jaName: "まもる" },
      { slug: "encore", jaName: "アンコール" },
      { slug: "dazzling-gleam", jaName: "マジカルシャイン" },
    ],
  },
  // 73位: ブリムオン
  "hatterene": {
    slug: "hatterene",
    jaName: "ブリムオン",
    rank: 73,
    abilities: [
      { slug: "magic-bounce", isHidden: true, slot: 3 },
      { slug: "healer", isHidden: false, slot: 2 },
      { slug: "anticipation", isHidden: false, slot: 3 },
    ],
    moves: [
      { slug: "trick-room", jaName: "トリックルーム" },
      { slug: "psychic-noise", jaName: "サイコノイズ" },
      { slug: "misty-explosion", jaName: "ミストバースト" },
      { slug: "draining-kiss", jaName: "ドレインキッス" },
      { slug: "dazzling-gleam", jaName: "マジカルシャイン" },
      { slug: "healing-wish", jaName: "いやしのねがい" },
      { slug: "mystical-fire", jaName: "マジカルフレイム" },
      { slug: "calm-mind", jaName: "めいそう" },
      { slug: "psychic", jaName: "サイコキネシス" },
      { slug: "pain-split", jaName: "いたみわけ" },
    ],
  },
  // 74位: トドロクツキ
  "roaring-moon": {
    slug: "roaring-moon",
    jaName: "トドロクツキ",
    rank: 74,
    abilities: [
      { slug: "protosynthesis", isHidden: false, slot: 1 },
    ],
    moves: [
      { slug: "knock-off", jaName: "はたきおとす" },
      { slug: "earthquake", jaName: "じしん" },
      { slug: "dragon-dance", jaName: "りゅうのまい" },
      { slug: "outrage", jaName: "げきりん" },
      { slug: "u-turn", jaName: "とんぼがえり" },
      { slug: "taunt", jaName: "ちょうはつ" },
      { slug: "roost", jaName: "はねやすめ" },
      { slug: "iron-head", jaName: "アイアンヘッド" },
      { slug: "acrobatics", jaName: "アクロバット" },
      { slug: "jaw-lock", jaName: "くらいつく" },
    ],
  },
  // 76位: キュウコン (アローラ)
  "ninetales-alola": {
    slug: "ninetales-alola",
    jaName: "キュウコン (アローラ)",
    rank: 76,
    abilities: [
      { slug: "snow-warning", isHidden: false, slot: 1 },
      { slug: "snow-cloak", isHidden: true, slot: 3 },
    ],
    moves: [
      { slug: "aurora-veil", jaName: "オーロラベール" },
      { slug: "moonblast", jaName: "ムーンフォース" },
      { slug: "encore", jaName: "アンコール" },
      { slug: "blizzard", jaName: "ふぶき" },
      { slug: "freeze-dry", jaName: "フリーズドライ" },
      { slug: "icy-wind", jaName: "こごえるかぜ" },
      { slug: "ice-shard", jaName: "こおりのつぶて" },
      { slug: "pain-split", jaName: "いたみわけ" },
      { slug: "misty-terrain", jaName: "ミストフィールド" },
      { slug: "tera-blast", jaName: "テラバースト" },
    ],
  },
  // 77位: タケルライコ
  "raging-bolt": {
    slug: "raging-bolt",
    jaName: "タケルライコ",
    rank: 77,
    abilities: [
      { slug: "protosynthesis", isHidden: false, slot: 1 },
    ],
    moves: [
      { slug: "thunderclap", jaName: "じんらい" },
      { slug: "draco-meteor", jaName: "りゅうせいぐん" },
      { slug: "thunderbolt", jaName: "１０まんボルト" },
      { slug: "volt-switch", jaName: "ボルトチェンジ" },
      { slug: "tera-blast", jaName: "テラバースト" },
      { slug: "dragon-pulse", jaName: "りゅうのはどう" },
      { slug: "calm-mind", jaName: "めいそう" },
      { slug: "discharge", jaName: "ほうでん" },
      { slug: "snarl", jaName: "バークアウト" },
      { slug: "rising-voltage", jaName: "ライジングボルト" },
    ],
  },
  // 78位: ブラッキー
  "umbreon": {
    slug: "umbreon",
    jaName: "ブラッキー",
    rank: 78,
    abilities: [
      { slug: "inner-focus", isHidden: true, slot: 3 },
      { slug: "synchronize", isHidden: false, slot: 2 },
    ],
    moves: [
      { slug: "foul-play", jaName: "イカサマ" },
      { slug: "protect", jaName: "まもる" },
      { slug: "wish", jaName: "ねがいごと" },
      { slug: "toxic", jaName: "どくどく" },
      { slug: "moonlight", jaName: "つきのひかり" },
      { slug: "yawn", jaName: "あくび" },
      { slug: "taunt", jaName: "ちょうはつ" },
      { slug: "snarl", jaName: "バークアウト" },
      { slug: "curse", jaName: "のろい" },
      { slug: "roar", jaName: "ほえる" },
    ],
  },
  // 79位: ギラティナ (オリジン)
  "giratina-origin": {
    slug: "giratina-origin",
    jaName: "ギラティナ (オリジン)",
    rank: 79,
    abilities: [
      { slug: "levitate", isHidden: false, slot: 1 },
    ],
    moves: [
      { slug: "shadow-sneak", jaName: "かげうち" },
      { slug: "draco-meteor", jaName: "りゅうせいぐん" },
      { slug: "poltergeist", jaName: "ポルターガイスト" },
      { slug: "hex", jaName: "たたりめ" },
      { slug: "curse", jaName: "のろい" },
      { slug: "will-o-wisp", jaName: "おにび" },
      { slug: "dragon-claw", jaName: "ドラゴンクロー" },
      { slug: "thunder-wave", jaName: "でんじは" },
      { slug: "iron-head", jaName: "アイアンヘッド" },
      { slug: "earthquake", jaName: "じしん" },
    ],
  },
  // 80位: テツノカイナ
  "iron-hands": {
    slug: "iron-hands",
    jaName: "テツノカイナ",
    rank: 80,
    abilities: [
      { slug: "quark-drive", isHidden: false, slot: 1 },
    ],
    moves: [
      { slug: "drain-punch", jaName: "ドレインパンチ" },
      { slug: "ice-punch", jaName: "れいとうパンチ" },
      { slug: "supercell-slam", jaName: "サンダーダイブ" },
      { slug: "fake-out", jaName: "ねこだまし" },
      { slug: "swords-dance", jaName: "つるぎのまい" },
      { slug: "earthquake", jaName: "じしん" },
      { slug: "thunder-punch", jaName: "かみなりパンチ" },
      { slug: "volt-switch", jaName: "ボルトチェンジ" },
      { slug: "play-rough", jaName: "じゃれつく" },
      { slug: "substitute", jaName: "みがわり" },
    ],
  },
  // 81位: ヌメルゴン (ヒスイ)
  "goodra-hisui": {
    slug: "goodra-hisui",
    jaName: "ヌメルゴン (ヒスイ)",
    rank: 81,
    abilities: [
      { slug: "sap-sipper", isHidden: false, slot: 1 },
      { slug: "shell-armor", isHidden: false, slot: 2 },
      { slug: "gooey", isHidden: true, slot: 3 },
    ],
    moves: [
      { slug: "knock-off", jaName: "はたきおとす" },
      { slug: "flash-cannon", jaName: "ラスターカノン" },
      { slug: "draco-meteor", jaName: "りゅうせいぐん" },
      { slug: "acid-spray", jaName: "アシッドボム" },
      { slug: "heavy-slam", jaName: "ヘビーボンバー" },
      { slug: "ice-beam", jaName: "れいとうビーム" },
      { slug: "dragon-tail", jaName: "ドラゴンテール" },
      { slug: "earthquake", jaName: "じしん" },
      { slug: "thunderbolt", jaName: "１０まんボルト" },
      { slug: "iron-head", jaName: "アイアンヘッド" },
    ],
  },
  // 82位: フォレトス
  "forretress": {
    slug: "forretress",
    jaName: "フォレトス",
    rank: 82,
    abilities: [
      { slug: "sturdy", isHidden: false, slot: 1 },
      { slug: "overcoat", isHidden: true, slot: 3 },
    ],
    moves: [
      { slug: "toxic-spikes", jaName: "どくびし" },
      { slug: "body-press", jaName: "ボディプレス" },
      { slug: "stealth-rock", jaName: "ステルスロック" },
      { slug: "rapid-spin", jaName: "こうそくスピン" },
      { slug: "gyro-ball", jaName: "ジャイロボール" },
      { slug: "volt-switch", jaName: "ボルトチェンジ" },
      { slug: "pain-split", jaName: "いたみわけ" },
      { slug: "counter", jaName: "カウンター" },
      { slug: "payback", jaName: "しっぺがえし" },
      { slug: "curse", jaName: "のろい" },
    ],
  },
  // 83位: ウインディ
  "arcanine": {
    slug: "arcanine",
    jaName: "ウインディ",
    rank: 83,
    abilities: [
      { slug: "intimidate", isHidden: false, slot: 1 },
      { slug: "flash-fire", isHidden: false, slot: 2 },
      { slug: "justified", isHidden: true, slot: 3 },
    ],
    moves: [
      { slug: "morning-sun", jaName: "あさのひざし" },
      { slug: "will-o-wisp", jaName: "おにび" },
      { slug: "extreme-speed", jaName: "しんそく" },
      { slug: "flare-blitz", jaName: "フレアドライブ" },
      { slug: "play-rough", jaName: "じゃれつく" },
      { slug: "bulldoze", jaName: "じならし" },
      { slug: "roar", jaName: "ほえる" },
      { slug: "flamethrower", jaName: "かえんほうしゃ" },
      { slug: "charm", jaName: "あまえる" },
      { slug: "curse", jaName: "のろい" },
    ],
  },
  // 84位: セグレイブ
  "baxcalibur": {
    slug: "baxcalibur",
    jaName: "セグレイブ",
    rank: 84,
    abilities: [
      { slug: "thermal-exchange", isHidden: false, slot: 1 },
      { slug: "ice-body", isHidden: true, slot: 3 },
    ],
    moves: [
      { slug: "ice-shard", jaName: "こおりのつぶて" },
      { slug: "icicle-spear", jaName: "つららばり" },
      { slug: "earthquake", jaName: "じしん" },
      { slug: "scale-shot", jaName: "スケイルショット" },
      { slug: "dragon-dance", jaName: "りゅうのまい" },
      { slug: "glaive-rush", jaName: "きょけんとつげき" },
      { slug: "swords-dance", jaName: "つるぎのまい" },
      { slug: "icicle-crash", jaName: "つららおとし" },
      { slug: "tera-blast", jaName: "テラバースト" },
      { slug: "crunch", jaName: "かみくだく" },
    ],
  },
  // 85位: ハリーマン
  "overqwil": {
    slug: "overqwil",
    jaName: "ハリーマン",
    rank: 85,
    abilities: [
      { slug: "intimidate", isHidden: true, slot: 3 },
      { slug: "swift-swim", isHidden: false, slot: 2 },
      { slug: "poison-point", isHidden: false, slot: 3 },
    ],
    moves: [
      { slug: "barb-barrage", jaName: "どくばりセンボン" },
      { slug: "toxic-spikes", jaName: "どくびし" },
      { slug: "crunch", jaName: "かみくだく" },
      { slug: "taunt", jaName: "ちょうはつ" },
      { slug: "spikes", jaName: "まきびし" },
      { slug: "toxic", jaName: "どくどく" },
      { slug: "destiny-bond", jaName: "みちづれ" },
      { slug: "protect", jaName: "まもる" },
      { slug: "endure", jaName: "こらえる" },
      { slug: "minimize", jaName: "ちいさくなる" },
    ],
  },
  // 86位: ラグラージ
  "swampert": {
    slug: "swampert",
    jaName: "ラグラージ",
    rank: 86,
    abilities: [
      { slug: "torrent", isHidden: false, slot: 1 },
      { slug: "damp", isHidden: true, slot: 3 },
    ],
    moves: [
      { slug: "flip-turn", jaName: "クイックターン" },
      { slug: "knock-off", jaName: "はたきおとす" },
      { slug: "stealth-rock", jaName: "ステルスロック" },
      { slug: "earthquake", jaName: "じしん" },
      { slug: "yawn", jaName: "あくび" },
      { slug: "mirror-coat", jaName: "ミラーコート" },
      { slug: "roar", jaName: "ほえる" },
      { slug: "endeavor", jaName: "がむしゃら" },
      { slug: "counter", jaName: "カウンター" },
      { slug: "liquidation", jaName: "アクアブレイク" },
    ],
  },
  // 87位: イダイトウ (オス)
  "basculegion": {
    slug: "basculegion",
    jaName: "イダイトウ (オス)",
    rank: 87,
    abilities: [
      { slug: "adaptability", isHidden: false, slot: 1 },
      { slug: "swift-swim", isHidden: false, slot: 2 },
      { slug: "mold-breaker", isHidden: true, slot: 3 },
    ],
    moves: [
      { slug: "last-respects", jaName: "おはかまいり" },
      { slug: "aqua-jet", jaName: "アクアジェット" },
      { slug: "wave-crash", jaName: "ウェーブタックル" },
      { slug: "substitute", jaName: "みがわり" },
      { slug: "flip-turn", jaName: "クイックターン" },
      { slug: "psychic-fangs", jaName: "サイコファング" },
      { slug: "liquidation", jaName: "アクアブレイク" },
      { slug: "head-smash", jaName: "もろはのずつき" },
      { slug: "agility", jaName: "こうそくいどう" },
      { slug: "endure", jaName: "こらえる" },
    ],
  },
  // 88位: パルシェン
  "cloyster": {
    slug: "cloyster",
    jaName: "パルシェン",
    rank: 88,
    abilities: [
      { slug: "skill-link", isHidden: false, slot: 1 },
      { slug: "shell-armor", isHidden: false, slot: 2 },
    ],
    moves: [
      { slug: "icicle-spear", jaName: "つららばり" },
      { slug: "shell-smash", jaName: "からをやぶる" },
      { slug: "rock-blast", jaName: "ロックブラスト" },
      { slug: "ice-shard", jaName: "こおりのつぶて" },
      { slug: "drill-run", jaName: "ドリルライナー" },
      { slug: "toxic-spikes", jaName: "どくびし" },
      { slug: "tera-blast", jaName: "テラバースト" },
      { slug: "liquidation", jaName: "アクアブレイク" },
      { slug: "substitute", jaName: "みがわり" },
      { slug: "protect", jaName: "まもる" },
    ],
  },
  // 89位: テツノカシラ
  "iron-crown": {
    slug: "iron-crown",
    jaName: "テツノカシラ",
    rank: 89,
    abilities: [
      { slug: "quark-drive", isHidden: false, slot: 1 },
    ],
    moves: [
      { slug: "tachyon-cutter", jaName: "タキオンカッター" },
      { slug: "psychic-noise", jaName: "サイコノイズ" },
      { slug: "volt-switch", jaName: "ボルトチェンジ" },
      { slug: "future-sight", jaName: "みらいよち" },
      { slug: "metal-burst", jaName: "メタルバースト" },
      { slug: "psyshock", jaName: "サイコショック" },
      { slug: "tera-blast", jaName: "テラバースト" },
      { slug: "calm-mind", jaName: "めいそう" },
      { slug: "substitute", jaName: "みがわり" },
      { slug: "psychic", jaName: "サイコキネシス" },
    ],
  },
  // 90位: イダイナキバ
  "great-tusk": {
    slug: "great-tusk",
    jaName: "イダイナキバ",
    rank: 90,
    abilities: [
      { slug: "protosynthesis", isHidden: false, slot: 1 },
    ],
    moves: [
      { slug: "knock-off", jaName: "はたきおとす" },
      { slug: "rapid-spin", jaName: "こうそくスピン" },
      { slug: "stealth-rock", jaName: "ステルスロック" },
      { slug: "earthquake", jaName: "じしん" },
      { slug: "close-combat", jaName: "インファイト" },
      { slug: "bulldoze", jaName: "じならし" },
      { slug: "headlong-rush", jaName: "ぶちかまし" },
      { slug: "ice-spinner", jaName: "アイススピナー" },
      { slug: "head-smash", jaName: "もろはのずつき" },
      { slug: "taunt", jaName: "ちょうはつ" },
    ],
  },
  // 91位: クレッフィ
  "klefki": {
    slug: "klefki",
    jaName: "クレッフィ",
    rank: 91,
    abilities: [
      { slug: "prankster", isHidden: false, slot: 1 },
      { slug: "magician", isHidden: true, slot: 3 },
    ],
    moves: [
      { slug: "reflect", jaName: "リフレクター" },
      { slug: "light-screen", jaName: "ひかりのかべ" },
      { slug: "steel-beam", jaName: "てっていこうせん" },
      { slug: "thunder-wave", jaName: "でんじは" },
      { slug: "spikes", jaName: "まきびし" },
      { slug: "foul-play", jaName: "イカサマ" },
      { slug: "draining-kiss", jaName: "ドレインキッス" },
      { slug: "switcheroo", jaName: "すりかえ" },
      { slug: "misty-terrain", jaName: "ミストフィールド" },
      { slug: "trick-room", jaName: "トリックルーム" },
    ],
  },
  // 92位: エーフィ
  "espeon": {
    slug: "espeon",
    jaName: "エーフィ",
    rank: 92,
    abilities: [
      { slug: "magic-bounce", isHidden: true, slot: 3 },
      { slug: "synchronize", isHidden: false, slot: 2 },
    ],
    moves: [
      { slug: "calm-mind", jaName: "めいそう" },
      { slug: "alluring-voice", jaName: "みわくのボイス" },
      { slug: "morning-sun", jaName: "あさのひざし" },
      { slug: "stored-power", jaName: "アシストパワー" },
      { slug: "psychic-noise", jaName: "サイコノイズ" },
      { slug: "psychic", jaName: "サイコキネシス" },
      { slug: "trick", jaName: "トリック" },
      { slug: "shadow-ball", jaName: "シャドーボール" },
      { slug: "draining-kiss", jaName: "ドレインキッス" },
      { slug: "baton-pass", jaName: "バトンタッチ" },
    ],
  },
  // 93位: マンムー
  "mamoswine": {
    slug: "mamoswine",
    jaName: "マンムー",
    rank: 93,
    abilities: [
      { slug: "oblivious", isHidden: false, slot: 1 },
      { slug: "thick-fat", isHidden: true, slot: 3 },
      { slug: "snow-cloak", isHidden: false, slot: 3 },
    ],
    moves: [
      { slug: "ice-shard", jaName: "こおりのつぶて" },
      { slug: "earthquake", jaName: "じしん" },
      { slug: "knock-off", jaName: "はたきおとす" },
      { slug: "icicle-spear", jaName: "つららばり" },
      { slug: "icicle-crash", jaName: "つららおとし" },
      { slug: "endeavor", jaName: "がむしゃら" },
      { slug: "rock-blast", jaName: "ロックブラスト" },
      { slug: "stone-edge", jaName: "ストーンエッジ" },
      { slug: "stealth-rock", jaName: "ステルスロック" },
      { slug: "tera-blast", jaName: "テラバースト" },
    ],
  },
  // 94位: ギャラドス
  "gyarados": {
    slug: "gyarados",
    jaName: "ギャラドス",
    rank: 94,
    abilities: [
      { slug: "intimidate", isHidden: false, slot: 1 },
      { slug: "moxie", isHidden: true, slot: 3 },
    ],
    moves: [
      { slug: "earthquake", jaName: "じしん" },
      { slug: "waterfall", jaName: "たきのぼり" },
      { slug: "taunt", jaName: "ちょうはつ" },
      { slug: "thunder-wave", jaName: "でんじは" },
      { slug: "dragon-dance", jaName: "りゅうのまい" },
      { slug: "ice-fang", jaName: "こおりのキバ" },
      { slug: "crunch", jaName: "かみくだく" },
      { slug: "tera-blast", jaName: "テラバースト" },
      { slug: "stone-edge", jaName: "ストーンエッジ" },
      { slug: "aqua-tail", jaName: "アクアテール" },
    ],
  },
  // 95位: ウェーニバル
  "quaquaval": {
    slug: "quaquaval",
    jaName: "ウェーニバル",
    rank: 95,
    abilities: [
      { slug: "moxie", isHidden: true, slot: 3 },
      { slug: "torrent", isHidden: false, slot: 2 },
    ],
    moves: [
      { slug: "aqua-step", jaName: "アクアステップ" },
      { slug: "close-combat", jaName: "インファイト" },
      { slug: "aqua-jet", jaName: "アクアジェット" },
      { slug: "triple-axel", jaName: "トリプルアクセル" },
      { slug: "endeavor", jaName: "がむしゃら" },
      { slug: "knock-off", jaName: "はたきおとす" },
      { slug: "encore", jaName: "アンコール" },
      { slug: "ice-spinner", jaName: "アイススピナー" },
      { slug: "bulk-up", jaName: "ビルドアップ" },
      { slug: "baton-pass", jaName: "バトンタッチ" },
    ],
  },
  // 96位: コノヨザル
  "annihilape": {
    slug: "annihilape",
    jaName: "コノヨザル",
    rank: 96,
    abilities: [
      { slug: "defiant", isHidden: true, slot: 3 },
      { slug: "vital-spirit", isHidden: false, slot: 2 },
      { slug: "inner-focus", isHidden: false, slot: 3 },
    ],
    moves: [
      { slug: "rage-fist", jaName: "ふんどのこぶし" },
      { slug: "drain-punch", jaName: "ドレインパンチ" },
      { slug: "final-gambit", jaName: "いのちがけ" },
      { slug: "bulk-up", jaName: "ビルドアップ" },
      { slug: "taunt", jaName: "ちょうはつ" },
      { slug: "close-combat", jaName: "インファイト" },
      { slug: "u-turn", jaName: "とんぼがえり" },
      { slug: "stealth-rock", jaName: "ステルスロック" },
      { slug: "shadow-claw", jaName: "シャドークロー" },
      { slug: "encore", jaName: "アンコール" },
    ],
  },
  // 97位: ピクシー
  "clefable": {
    slug: "clefable",
    jaName: "ピクシー",
    rank: 97,
    abilities: [
      { slug: "magic-guard", isHidden: false, slot: 1 },
      { slug: "unaware", isHidden: true, slot: 3 },
    ],
    moves: [
      { slug: "moonlight", jaName: "つきのひかり" },
      { slug: "stored-power", jaName: "アシストパワー" },
      { slug: "alluring-voice", jaName: "みわくのボイス" },
      { slug: "calm-mind", jaName: "めいそう" },
      { slug: "cosmic-power", jaName: "コスモパワー" },
      { slug: "moonblast", jaName: "ムーンフォース" },
      { slug: "substitute", jaName: "みがわり" },
      { slug: "baton-pass", jaName: "バトンタッチ" },
      { slug: "draining-kiss", jaName: "ドレインキッス" },
      { slug: "trick", jaName: "トリック" },
    ],
  },
  // 98位: ハピナス
  "blissey": {
    slug: "blissey",
    jaName: "ハピナス",
    rank: 98,
    abilities: [
      { slug: "natural-cure", isHidden: false, slot: 1 },
      { slug: "serene-grace", isHidden: false, slot: 2 },
      { slug: "healer", isHidden: true, slot: 3 },
    ],
    moves: [
      { slug: "soft-boiled", jaName: "タマゴうみ" },
      { slug: "calm-mind", jaName: "めいそう" },
      { slug: "ice-beam", jaName: "れいとうビーム" },
      { slug: "shadow-ball", jaName: "シャドーボール" },
      { slug: "thunder-wave", jaName: "でんじは" },
      { slug: "seismic-toss", jaName: "ちきゅうなげ" },
      { slug: "stealth-rock", jaName: "ステルスロック" },
      { slug: "flamethrower", jaName: "かえんほうしゃ" },
      { slug: "fling", jaName: "なげつける" },
      { slug: "trick", jaName: "トリック" },
    ],
  },
  // 99位: ゾロアーク (ヒスイ)
  "zoroark-hisui": {
    slug: "zoroark-hisui",
    jaName: "ゾロアーク (ヒスイ)",
    rank: 99,
    abilities: [
      { slug: "illusion", isHidden: false, slot: 1 },
    ],
    moves: [
      { slug: "bitter-malice", jaName: "うらみつらみ" },
      { slug: "trick", jaName: "トリック" },
      { slug: "curse", jaName: "のろい" },
      { slug: "shadow-sneak", jaName: "かげうち" },
      { slug: "knock-off", jaName: "はたきおとす" },
      { slug: "comeuppance", jaName: "ほうふく" },
      { slug: "will-o-wisp", jaName: "おにび" },
      { slug: "taunt", jaName: "ちょうはつ" },
      { slug: "shadow-ball", jaName: "シャドーボール" },
      { slug: "grass-knot", jaName: "くさむすび" },
    ],
  },
  // 100位: ジャローダ
  "serperior": {
    slug: "serperior",
    jaName: "ジャローダ",
    rank: 100,
    abilities: [
      { slug: "contrary", isHidden: true, slot: 3 },
      { slug: "overgrow", isHidden: false, slot: 2 },
    ],
    moves: [
      { slug: "leaf-storm", jaName: "リーフストーム" },
      { slug: "tera-blast", jaName: "テラバースト" },
      { slug: "glare", jaName: "へびにらみ" },
      { slug: "substitute", jaName: "みがわり" },
      { slug: "giga-drain", jaName: "ギガドレイン" },
      { slug: "dragon-pulse", jaName: "りゅうのはどう" },
      { slug: "leech-seed", jaName: "やどりぎのタネ" },
      { slug: "taunt", jaName: "ちょうはつ" },
      { slug: "mirror-coat", jaName: "ミラーコート" },
      { slug: "gastro-acid", jaName: "いえき" },
    ],
  },
};

/** マスターデータに含まれるポケモンのslug一覧 */
export const MASTER_DATA_SLUGS = new Set(Object.keys(POKEMON_MASTER_DATA));
